// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
// defineApp
export { defineApp } from './core/defineApp'
export type { RuntimeConfig } from './core/defineApp'
// plugins
export { Access, useAccess, useAccessMarkedRoutes } from '/Users/angelessgro/Documents/slingr/Untitled/framework/apps/project-management-app/frontend/src/.umi/plugin-access';
export { useAntdConfig, useAntdConfigSetter } from '/Users/angelessgro/Documents/slingr/Untitled/framework/apps/project-management-app/frontend/src/.umi/plugin-antd';
export { Provider, useModel } from '/Users/angelessgro/Documents/slingr/Untitled/framework/apps/project-management-app/frontend/src/.umi/plugin-model';
export { useRequest, UseRequestProvider, request, getRequestInstance } from '/Users/angelessgro/Documents/slingr/Untitled/framework/apps/project-management-app/frontend/src/.umi/plugin-request';
// plugins types.d.ts
export * from '/Users/angelessgro/Documents/slingr/Untitled/framework/apps/project-management-app/frontend/src/.umi/plugin-access/types.d';
export * from '/Users/angelessgro/Documents/slingr/Untitled/framework/apps/project-management-app/frontend/src/.umi/plugin-antd/types.d';
export * from '/Users/angelessgro/Documents/slingr/Untitled/framework/apps/project-management-app/frontend/src/.umi/plugin-layout/types.d';
export * from '/Users/angelessgro/Documents/slingr/Untitled/framework/apps/project-management-app/frontend/src/.umi/plugin-request/types.d';
// @umijs/renderer-*
export { createBrowserHistory, createHashHistory, createMemoryHistory, Helmet, HelmetProvider, createSearchParams, generatePath, matchPath, matchRoutes, Navigate, NavLink, Outlet, resolvePath, useLocation, useMatch, useNavigate, useOutlet, useOutletContext, useParams, useResolvedPath, useRoutes, useSearchParams, useAppData, useClientLoaderData, useLoaderData, useRouteProps, useSelectedRoutes, useServerLoaderData, renderClient, __getRoot, Link, useRouteData, __useFetcher, withRouter } from '/Users/angelessgro/Documents/slingr/Untitled/framework/node_modules/.pnpm/@umijs+renderer-react@4.6.39_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/@umijs/renderer-react';
export type { History, ClientLoader } from '/Users/angelessgro/Documents/slingr/Untitled/framework/node_modules/.pnpm/@umijs+renderer-react@4.6.39_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/@umijs/renderer-react'
// umi/client/client/plugin
export { ApplyPluginsType, PluginManager } from '/Users/angelessgro/Documents/slingr/Untitled/framework/node_modules/.pnpm/umi@4.6.39_@babel+core@7.29.0_@types+node@22.19.15_@types+react@18.3.28_eslint@8.35.0_j_d956e818361144018c4e18c08cc7c97b/node_modules/umi/client/client/plugin.js';
export { history, createHistory } from './core/history';
export { terminal } from './core/terminal';
// react ssr
export const useServerInsertedHTML: Function = () => {};
// test
export { TestBrowser } from './testBrowser';
