// Side-effect import: ensures ReportQueue's @Queue decorator runs and registers 'report-queue'.
import '@/config/queues/processors.queue';
import {
	BaseDataModel,
	BaseWorkflow,
	DataModel,
	Step,
	SystemQueue,
	storageService,
	TextField,
	Workflow,
} from '@drumr/framework-backend';
import PDFDocument from 'pdfkit';
import { MainDs } from '@/config/data-sources/main/main.ds';
import { Project } from '@/projects/data-models/project.data-model';
import { ProjectReport } from '@/projects/data-models/project-report.data-model';
import { File } from '@/support/data-models/file.data-model';

type ProjectSnapshot = Record<string, unknown>;

interface ReportStats {
	total: number;
	active: number;
	totalBudget: number;
	generatedAt: string;
}

@DataModel({
	ui: {
		crud: {
			api: 'gql',
		},
	},
})
export class GenerateReportParams extends BaseDataModel {
	@TextField({
		required: true,
		docs: 'Title of the report',
	})
	title!: string;

	@TextField({
		required: true,
		docs: 'Sections to include in the report',
	})
	sections!: string[];
}

@Workflow({
	queue: 'report-queue',
})
export class GenerateReportWorkflow extends BaseWorkflow {
	constructor(private ds: MainDs) {
		super();
	}

	async execute(params: GenerateReportParams): Promise<string> {
		await this.reportProgress(0, { message: 'Starting report generation' });
		const projectsData = await this.callStep(this.fetchProjectsData, params);
		await this.reportProgress(50, { message: 'Aggregating data' });
		const stats = await this.callStep(this.aggregateStats, projectsData);
		await this.reportProgress(80, { message: 'Generating PDF report' });
		const reportUrl = await this.callStep(this.generatePdf, {
			stats,
			title: params.title,
		});
		return reportUrl;
	}

	@Step({ transactional: false })
	async fetchProjectsData(
		params: GenerateReportParams,
	): Promise<ProjectSnapshot[]> {
		// Keep params in signature to preserve current workflow contract.
		void params;
		const projects: Project[] = [];
		await this.ds.findAndPaginate(
			Project,
			{
				where: {},
				orderBy: { id: 'ASC' },
			},
			async (project) => {
				projects.push(project);
				return true;
			},
		);

		if (!projects) {
			throw new Error('No projects found');
		}
		return projects.map((p) => p.toJSON());
	}

	@Step({})
	async aggregateStats(projects: ProjectSnapshot[]): Promise<ReportStats> {
		const total = projects.length;
		const active = projects.filter((p) => p.status === 'active').length;

		const totalBudgetPrecise = projects.reduce((acc: any, p) => {
			try {
				return acc.plus(money(p.budget != null ? String(p.budget) : '0'));
			} catch {
				return acc;
			}
		}, money(0));

		const totalBudget = Number(totalBudgetPrecise.toString());

		await new Promise((resolve) => setTimeout(resolve, 10000));
		return {
			total,
			active,
			totalBudget,
			generatedAt: new Date().toISOString(),
		};
	}

	@Step({
		retries: 3,
		retryDelay: 1000,
		backoff: 'exponential',
		queue: SystemQueue,
	})
	async generatePdf(input: {
		stats: ReportStats;
		title: string;
	}): Promise<string> {
		const filename = `report_${input.title.toLowerCase().replace(/\s+/g, '_')}_${Date.now()}.pdf`;

		const doc = new PDFDocument();
		const chunks: Buffer[] = [];
		doc.on('data', (chunk) => chunks.push(chunk));

		const pdfBufferPromise = new Promise<Buffer>((resolve, reject) => {
			doc.on('end', () => resolve(Buffer.concat(chunks)));
			doc.on('error', reject);
		});

		doc.fontSize(20).text(input.title, { align: 'center' });
		doc.moveDown();
		doc
			.fontSize(12)
			.fillColor('gray')
			.text(`Generated at: ${new Date().toLocaleString()}`, {
				align: 'center',
			});
		doc.moveDown(2);

		doc.fontSize(16).text('Project Statistics', { underline: true });
		doc.moveDown();

		doc.fontSize(12).fillColor('black');
		doc.text(`Total Projects: ${input.stats.total}`);
		doc.moveDown(0.5);
		doc.text(`Active Projects: ${input.stats.active}`);
		doc.moveDown(0.5);
		doc.text(`Total Budget: $${input.stats.totalBudget.toLocaleString()}`);

		doc.moveDown(2);
		doc
			.fontSize(10)
			.text('Generated by Tasky app', 50, 700, { align: 'center', width: 500 });

		doc.end();

		const pdfBuffer = await pdfBufferPromise;

		const fileInfo = await storageService.upload(pdfBuffer, filename, {
			contentType: 'application/pdf',
		});
		if (!fileInfo.id) {
			throw new Error('Uploaded file did not return an id');
		}

		const pdfFile = new File();
		pdfFile.id = fileInfo.id;
		pdfFile.name = `projectsReport-${Date.now()}`;
		pdfFile.contentType = fileInfo.contentType || 'application/pdf';
		pdfFile.size = fileInfo.size;
		pdfFile.description = `Generated report: ${input.title}`;
		await this.ds.save(pdfFile);

		const report = new ProjectReport();
		report.title = input.title;
		report.generatedAt = new Date();
		report.file = pdfFile;

		await this.ds.save(report);
		return `/files/${pdfFile.id}`;
	}
}
