export interface AppMetadataField {
  name: string;
  [key: string]: unknown;
}

export interface AppMetadataModel {
  name: string;
  fields?: AppMetadataField[];
  [key: string]: unknown;
}

export interface AppMetadataAction {
  /** Action name as it appears in the UI (e.g. "Assign", "Archive", "Export") */
  name: string;
  /** Optional model scope — if absent the action is considered global */
  model?: string;
}

export interface AppMetadata {
  appName?: string;
  models?: AppMetadataModel[];
  entities?: AppMetadataModel[];
  /**
   * Optional list of UI actions available in the app.
   * When supplied, the QA Analyst cross-validates that acceptance criteria
   * referencing non-CRUD verbs (assign, archive, export, etc.) have a
   * matching entry here. Missing entries are surfaced as `warning` ambiguities
   * so they are caught before the coder agent generates unreachable test steps.
   */
  actions?: AppMetadataAction[];
  [key: string]: unknown;
}

export interface RequirementRequest {
  userStory: string;
  acceptanceCriteria: string[];
  /** Optional linked application metadata JSON schema generated by design agents */
  appMetadata?: AppMetadata;
}

// ---------------------------------------------------------------------------
// Analyst input sources — normalised into RequirementRequest before analysis
// ---------------------------------------------------------------------------

/**
 * The user provides user story and acceptance criteria directly.
 * Optionally enriched with appMetadata for cross-validation (dual mode).
 */
export interface StandaloneInput {
  kind: 'standalone';
  userStory: string;
  acceptanceCriteria: string[];
  appMetadata?: AppMetadata;
}

/**
 * Requirements come from a GitHub issue.
 * The adapter extracts the user story from the issue title (or an "As a …"
 * sentence in the body) and acceptance criteria from checklist / numbered
 * list items under an "Acceptance Criteria" section.
 */
export interface GitHubIssueInput {
  kind: 'github-issue';
  issue: {
    title: string;
    body: string;
    labels?: string[];
  };
  /** Optionally supply app metadata for dual-mode cross-validation */
  appMetadata?: AppMetadata;
}

/**
 * The agent has access to the application source files.
 * The adapter scans the provided path for entity/model class declarations
 * and action registrations, then builds appMetadata automatically.
 * Requirements must still be supplied explicitly.
 */
export interface AppCodebaseInput {
  kind: 'app-codebase';
  /** Absolute path to the directory containing TypeScript source files (e.g. backend/src) */
  sourcePath: string;
  userStory: string;
  acceptanceCriteria: string[];
}

/**
 * Only app metadata is available — no user story or criteria supplied.
 * The adapter synthesises baseline CRUD acceptance criteria for each entity.
 * Useful for full-app coverage baseline or brownfield audit passes.
 */
export interface MetadataOnlyInput {
  kind: 'metadata-only';
  appMetadata: AppMetadata;
  /**
   * Optional focus area description used as the user story.
   * When absent, a generic story is generated from the entity list.
   */
  focusArea?: string;
}

/** Discriminated union of all supported analyst input sources */
export type AnalystInput =
  | StandaloneInput
  | GitHubIssueInput
  | AppCodebaseInput
  | MetadataOnlyInput;

export interface AmbiguityReport {
  field: string;
  finding: string;
  severity: 'blocker' | 'warning' | 'info';
  recommendation: string;
}

export interface TestableBehavior {
  id: string;
  title: string;
  flowSteps: string[];
  expectedOutcomes: string[];
  type: 'positive' | 'negative' | 'boundary' | 'permission';
}

export interface BusinessFlow {
  name: string;
  behaviorIds: string[];
}

export type RiskType = 'security' | 'performance' | 'missing-negative' | 'missing-boundary' | 'missing-permission';

export interface RiskReport {
  behaviorId: string;
  riskType: RiskType;
  description: string;
}

export interface QAAnalysisResult {
  id: string;
  appName: string;
  functionalScope: {
    coveredEntities: string[];
    actors: string[];
    testedEndpoints: string[];
  };
  testableBehaviors: TestableBehavior[];
  businessFlows: BusinessFlow[];
  ambiguities: AmbiguityReport[];
  risks: RiskReport[];
  rulesApplied: string[];
  generatedAt: string;
}

// ---------------------------------------------------------------------------
// QA Test Generator Agent types
// ---------------------------------------------------------------------------

export interface GherkinStep {
  keyword: 'Given' | 'When' | 'Then' | 'And' | 'But';
  text: string;
}

export interface GherkinScenario {
  title: string;
  steps: GherkinStep[];
}

export interface TestCaseDefinition {
  id: string;
  behaviorId: string;
  title: string;
  type: 'positive' | 'negative' | 'boundary' | 'permission';
  gherkin: GherkinScenario;
  preconditions: string[];
  assertions: string[];
}

export interface CoverageMetric {
  totalBehaviors: number;
  coveredBehaviors: number;
  percentage: number;
  uncoveredBehaviors: string[];
}

export interface QATestGeneratorResult {
  id: string;
  analysisId: string;
  testCases: TestCaseDefinition[];
  coverage: CoverageMetric;
  generatedAt: string;
}

export interface QAAutomationCoderResult {
  id: string; // UUID
  generatorId: string; // References QATestGeneratorResult.id
  generatedFiles: {
    filePath: string; // e.g. "apps/project-management-app/frontend/tests/e2e/Task.spec.ts"
    content: string; // Fully compiled Playwright test file string
  }[];
  generatedAt: string;
}
