import { expect, type Locator, type Page, test } from '@playwright/test';
import { DrumrTestKit } from '@drumr/framework-qa/drumr-test-kit';

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

async function clearAutoGeneratedNotes(page: Page): Promise<void> {
  const notesCard = page
    .locator('.ant-card')
    .filter({ hasText: /^Notes$/i })
    .first();
  let hasNote = await notesCard
    .getByRole('button', { name: /delete/i })
    .first()
    .waitFor({ state: 'visible', timeout: 6_000 })
    .then(() => true)
    .catch(() => false);

  while (hasNote) {
    await notesCard
      .getByRole('button', { name: /delete/i })
      .first()
      .click();
    await page.waitForTimeout(400);
    hasNote = await notesCard
      .getByRole('button', { name: /delete/i })
      .first()
      .isVisible()
      .catch(() => false);
  }
}

async function createTaskWithStatus(
  page: Page,
  title: string,
  status: 'In Review' | 'In Progress',
): Promise<void> {
  const app = new DrumrTestKit(page);
  await app.navigateTo('/tasks/new');
  const titleInput = page.getByRole('textbox', { name: /title/i }).first();
  await titleInput.waitFor({ state: 'visible', timeout: 30_000 });
  await titleInput.fill(title);
  await app.selectFirstOption('Project');
  await page.waitForTimeout(1500);
  await app.selectOption('Status', status);
  await app.fillDateField('startedAt', '2026-05-13');
  await clearAutoGeneratedNotes(page);
  await app.submitCreate();
}

async function deleteTask(page: Page, title: string): Promise<void> {
  const app = new DrumrTestKit(page);
  await app.navigateTo('/tasks');
  await app.waitForTable();
  await app.clickTaskRowByTitle(title);
  await app.waitForDrawer();
  await app.clickManageDropdown();
  await app.clickManageOption(/delete/i);
  await app.confirmDelete();
}

async function openApproveTaskDialog(
  page: Page,
  taskTitle: string,
): Promise<Locator> {
  const app = new DrumrTestKit(page);
  await app.navigateTo('/tasks');
  await app.waitForTable();
  await app.clickTaskRowByTitle(taskTitle);
  await app.waitForDrawer();
  await app.clickActionsDropdown();
  await app.clickActionOption(/approve task/i);

  const dialog = page.getByRole('dialog', {
    name: /Approve Task/i,
  });
  await dialog.waitFor({ state: 'visible', timeout: 25_000 });
  return dialog;
}

async function getWorkflowCheckbox(dialog: Locator): Promise<Locator> {
  const workflowField = dialog
    .locator('.ant-form-item')
    .filter({ hasText: /execute.*work.*flow/i })
    .first();
  await expect(workflowField).toBeVisible({ timeout: 10_000 });

  const checkbox = workflowField.locator('input[type="checkbox"]').first();
  await expect(checkbox).toBeVisible({ timeout: 10_000 });
  return checkbox;
}

async function expectTaskReadViewDone(
  page: Page,
  taskTitle: string,
): Promise<void> {
  const app = new DrumrTestKit(page);
  await app.navigateTo('/tasks');
  await app.waitForTable();
  await app.clickTaskRowByTitle(taskTitle);
  await app.waitForDrawer();

  const drawer = page.locator('.ant-drawer:visible').last();
  await expect(drawer).toBeVisible({ timeout: 30_000 });
  await expect(
    drawer
      .getByText(new RegExp(`${escapeRegExp(taskTitle)}.*\\(DONE\\)`, 'i'))
      .first(),
  ).toBeVisible({ timeout: 30_000 });
}

test.describe
  .serial('Approve Task Action E2E', () => {
    let REVIEW_WORKFLOW_TASK_TITLE: string;
    let REVIEW_DIRECT_TASK_TITLE: string;
    let NON_REVIEW_TASK_TITLE: string;

    test.beforeAll(() => {
      const suffix = Date.now();
      REVIEW_WORKFLOW_TASK_TITLE = `ApproveTask-Workflow-${suffix}`;
      REVIEW_DIRECT_TASK_TITLE = `ApproveTask-Direct-${suffix}`;
      NON_REVIEW_TASK_TITLE = `ApproveTask-Blocked-${suffix}`;
    });

    test.setTimeout(120_000);

    test.beforeAll(async ({ browser }) => {
      test.setTimeout(180_000);
      const page = await browser.newPage();
      const app = new DrumrTestKit(page);
      await app.loginAsAdmin();

      await createTaskWithStatus(page, REVIEW_WORKFLOW_TASK_TITLE, 'In Review');
      await createTaskWithStatus(page, REVIEW_DIRECT_TASK_TITLE, 'In Review');
      await createTaskWithStatus(page, NON_REVIEW_TASK_TITLE, 'In Progress');

      await page.close();
    });

    test.afterAll(async ({ browser }) => {
      test.setTimeout(180_000);
      const page = await browser.newPage();
      const app = new DrumrTestKit(page);
      await app.loginAsAdmin();

      await deleteTask(page, REVIEW_WORKFLOW_TASK_TITLE);
      await deleteTask(page, REVIEW_DIRECT_TASK_TITLE);
      await deleteTask(page, NON_REVIEW_TASK_TITLE);

      await page.close();
    });

    test('shows Approve Task only for tasks in review', async ({ page }) => {
      const app = new DrumrTestKit(page);
      await app.loginAsAdmin();

      await app.navigateTo('/tasks');
      await app.waitForTable();
      await app.clickTaskRowByTitle(REVIEW_WORKFLOW_TASK_TITLE);
      await app.waitForDrawer();
      await app.clickActionsDropdown();
      await expect(
        page.getByRole('menuitem', { name: /approve task/i }),
      ).toBeVisible({ timeout: 10_000 });
      await page.keyboard.press('Escape');

      await app.navigateTo('/tasks');
      await app.waitForTable();
      await app.clickTaskRowByTitle(NON_REVIEW_TASK_TITLE);
      await app.waitForDrawer();
      await app.clickActionsDropdown();
      await expect(
        page.getByRole('menuitem', { name: /approve task/i }),
      ).toHaveCount(0, { timeout: 5_000 });
    });

    test('with workflow enabled, Approve Task shows inline workflow progress before closing', async ({
      page,
    }) => {
      const app = new DrumrTestKit(page);
      await app.loginAsAdmin();

      const dialog = await openApproveTaskDialog(
        page,
        REVIEW_WORKFLOW_TASK_TITLE,
      );
      const workflowCheckbox = await getWorkflowCheckbox(dialog);
      await expect(workflowCheckbox).toBeChecked();

      await app.clickOverlayButton(/execute/i);

      await expect(
        dialog.getByText(/the action is being executed in the background/i),
      ).toBeVisible({ timeout: 20_000 });

      await expect(dialog).toBeHidden({ timeout: 30_000 });
      await expectTaskReadViewDone(page, REVIEW_WORKFLOW_TASK_TITLE);
    });

    test('with workflow disabled, Approve Task closes normally without showing workflow progress', async ({
      page,
    }) => {
      const app = new DrumrTestKit(page);
      await app.loginAsAdmin();

      const dialog = await openApproveTaskDialog(
        page,
        REVIEW_DIRECT_TASK_TITLE,
      );
      const workflowCheckbox = await getWorkflowCheckbox(dialog);
      await workflowCheckbox.uncheck();
      await expect(workflowCheckbox).not.toBeChecked();

      await app.clickOverlayButton(/execute/i);

      const executionResult = await Promise.race([
        dialog
          .getByText(/the action is being executed in the background/i)
          .waitFor({ state: 'visible', timeout: 20_000 })
          .then(() => 'workflow' as const),
        dialog
          .waitFor({ state: 'hidden', timeout: 20_000 })
          .then(() => 'closed' as const),
      ]);

      expect(executionResult).toBe('closed');
      await expectTaskReadViewDone(page, REVIEW_DIRECT_TASK_TITLE);
    });
  });
