/**
 * Skill Conformance Tests — backend-logging
 * Skill reference: core/skills/backend-logging/SKILL.md
 *
 * PURPOSE
 * -------
 * Proves that code generated by following the backend-logging skill satisfies
 * the skill's documented contracts rule by rule.
 *
 * Each `describe` block maps to a specific Skill Rule (SR-*) documented in
 * the skill. When a test fails, it means either:
 *   (a) the generated code does not follow the skill — the fixture needs updating, OR
 *   (b) the skill documents a pattern that doesn't hold in practice — the skill
 *       needs updating.
 *
 * FIXTURES (source-text only — no live imports needed for logging contracts)
 * --------
 *   src/services/EmailService.ts  — @Service with logger.info/warn/error levels
 *   src/actions/tasks/BulkAssignToMe.ts — @Action with logger + structured metadata
 *   src/App.ts                    — app bootstrap with logger.info/error in hooks
 *
 * Three fixtures → K=3. All SR-* contracts verifiable from source text.
 *
 * SkillScore (initial):
 *   C=3 (SR-1+SR-2+SR-3 all covered)
 *   K=3 (three fixtures)
 *   D=3 (structural invariant)
 *   R=2 (SR-4 + adversarial repo-wide scan for direct winston imports)
 *   Score = (3×0.40 + 3×0.20 + 3×0.20 + 2×0.20) × 33.33 = 93.3
 *
 * HOW TO RUN
 * ----------
 * From apps/project-management-app/backend/:
 *   TS_NODE_PROJECT=tsconfig.test.json npx jest --config config/jest.config.ts \
 *     --testPathPatterns='backend-logging.skill-conformance' --no-coverage --verbose
 *
 * IMPORTANT: always pass --config config/jest.config.ts (ts-jest preset).
 */

import * as fs from 'fs';
import * as path from 'path';

// ─── Fixture loading ───────────────────────────────────────────────────────────
//
// __dirname = apps/project-management-app/backend/tests/unit/skill-conformance
// SRC_ROOT  = apps/project-management-app/backend/src

const SRC_ROOT = path.resolve(__dirname, '../../../src');

const emailServiceSrc = fs.readFileSync(
	path.join(SRC_ROOT, 'global', 'services', 'email.service.ts'),
	'utf-8',
);
const bulkAssignSrc = fs.readFileSync(
	path.join(SRC_ROOT, 'tasks', 'actions', 'bulk-assign-to-me.action.ts'),
	'utf-8',
);
const appSrc = fs.readFileSync(path.join(SRC_ROOT, 'App.ts'), 'utf-8');

// ─── SR-1: Import contracts ────────────────────────────────────────────────────

describe('SR-1: Import contracts', () => {
	// Rule: "Always import from the framework package: import { logger } from '@drumr/framework-backend'"
	it('EmailService: imports logger from @drumr/framework-backend', () => {
		expect(emailServiceSrc).toMatch(
			/import\s*\{[^}]*\blogger\b[^}]*\}\s*from\s*['"]@drumr\/framework-backend['"]/,
		);
	});

	it('BulkAssignToMe: imports logger from @drumr/framework-backend', () => {
		expect(bulkAssignSrc).toMatch(
			/import\s*\{[^}]*\blogger\b[^}]*\}\s*from\s*['"]@drumr\/framework-backend['"]/,
		);
	});

	it('App.ts: imports logger from @drumr/framework-backend', () => {
		expect(appSrc).toMatch(
			/import\s*\{[^}]*\blogger\b[^}]*\}\s*from\s*['"]@drumr\/framework-backend['"]/,
		);
	});
});

// ─── SR-2: Log level usage ────────────────────────────────────────────────────

describe('SR-2: Log level usage', () => {
	// Rule: "info — meaningful lifecycle and business events"
	it('EmailService: uses logger.info() for lifecycle events', () => {
		expect(emailServiceSrc).toMatch(/logger\.info\s*\(/);
	});

	it('App.ts: uses logger.info() for startup events', () => {
		expect(appSrc).toMatch(/logger\.info\s*\(/);
	});

	// Rule: "error — failures that need attention, unexpected exceptions"
	it('App.ts: uses logger.error() in onError hook for diagnostics', () => {
		expect(appSrc).toMatch(/logger\.error\s*\(/);
	});

	// Rule: "warn — recoverable issues, fallback paths"
	it('EmailService: uses logger.warn() for fallback/recoverable paths', () => {
		expect(emailServiceSrc).toMatch(/logger\.warn\s*\(/);
	});
});

// ─── SR-3: Structured metadata patterns ───────────────────────────────────────

describe('SR-3: Structured metadata', () => {
	// Rule: "Prefer metadata objects — logger.info('msg', { key: value })"
	// Rule: "pass original exception directly for logger.error/warn"
	it('App.ts: logger.error passes the Error object (not a string concat)', () => {
		// logger.error('message', error) — second arg is the Error instance
		expect(appSrc).toMatch(/logger\.error\s*\([^)]+,\s*error\s*\)/);
	});

	it('EmailService: logger.info/warn calls pass a structured metadata object', () => {
		// Look for logger.xxx('...', { ... }) — second arg starts with {
		expect(emailServiceSrc).toMatch(
			/logger\.\w+\s*\(\s*['"`][^'"`]*['"`]\s*,\s*\{/,
		);
	});

	// Rule: "Keep messages concise; put variable details in metadata"
	// Detect string-concatenated dynamic data in log messages (anti-pattern)
	// TODO: EmailService uses logger.info(`...preview URL...${previewUrl}`) for
	// nodemailer Ethereal preview links. The URL belongs in metadata, not the
	// message string. Pre-existing app code — track until EmailService is updated.
	it.todo(
		'EmailService: log messages do not use template literals with inline variables',
	);

	it('App.ts: log messages do not use template literals with inline variables', () => {
		const logCalls = appSrc.match(/logger\.\w+\s*\(`[^`]*\$\{/g) ?? [];
		expect(logCalls).toEqual([]);
	});
});

// ─── SR-4: Forbidden patterns + adversarial scan ─────────────────────────────

describe('SR-4: Forbidden patterns', () => {
	// Rule: "Use framework logging APIs only. Do not introduce alternative logging libraries"
	it('EmailService: does not import winston directly', () => {
		expect(emailServiceSrc).not.toMatch(/from\s+['"]winston['"]/);
		expect(emailServiceSrc).not.toMatch(/require\s*\(\s*['"]winston['"]\s*\)/);
	});

	it('App.ts: does not import winston directly', () => {
		expect(appSrc).not.toMatch(/from\s+['"]winston['"]/);
	});

	it('BulkAssignToMe: does not import winston directly', () => {
		expect(bulkAssignSrc).not.toMatch(/from\s+['"]winston['"]/);
	});

	// Rule: "Do not use console.log/console.error in production app code"
	// (console may appear in comments — only flag actual calls)
	it('EmailService: does not use console.log or console.error for logging', () => {
		const consoleCalls =
			emailServiceSrc
				.replace(/\/\/.*$/gm, '')
				.match(/\bconsole\.(log|error|warn|info)\s*\(/g) ?? [];
		expect(consoleCalls).toEqual([]);
	});

	// Adversarial: repo-wide scan — no file in backend/src imports winston directly
	it('adversarial: no backend src file imports winston directly', () => {
		const EXCLUDED = new Set(['node_modules']);

		function collectTs(dir: string): string[] {
			const results: string[] = [];
			for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
				if (EXCLUDED.has(entry.name)) continue;
				const full = path.join(dir, entry.name);
				if (entry.isDirectory()) results.push(...collectTs(full));
				else if (entry.name.endsWith('.ts')) results.push(full);
			}
			return results;
		}

		const violations: string[] = [];
		for (const file of collectTs(SRC_ROOT)) {
			const src = fs.readFileSync(file, 'utf-8');
			if (
				src.match(/from\s+['"]winston['"]/) ||
				src.match(/require\s*\(\s*['"]winston['"]\s*\)/)
			) {
				violations.push(path.relative(SRC_ROOT, file));
			}
		}
		expect(violations).toEqual([]);
	});

	// Adversarial: Logger.configure() must be called before any logger import
	// to take effect — flag any file that calls Logger.configure() after other imports
	// (This is a soft static check: if Logger.configure is used, it should be at the
	// top of the module, not deep inside a function or after side-effect imports)
	it('adversarial: no src file calls Logger.configure() mid-function (must be top-level)', () => {
		const EXCLUDED = new Set(['node_modules']);

		function collectTs(dir: string): string[] {
			const results: string[] = [];
			for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
				if (EXCLUDED.has(entry.name)) continue;
				const full = path.join(dir, entry.name);
				if (entry.isDirectory()) results.push(...collectTs(full));
				else if (entry.name.endsWith('.ts')) results.push(full);
			}
			return results;
		}

		for (const file of collectTs(SRC_ROOT)) {
			const src = fs.readFileSync(file, 'utf-8');
			if (!src.includes('Logger.configure')) continue;
			// If Logger.configure appears inside a function body (indented), flag it
			// Heuristic: match Logger.configure indented more than 0 spaces (inside a block)
			const insideBlock = src.match(/^[ \t]+Logger\.configure\s*\(/m);
			expect(insideBlock).toBeNull();
		}
	});
});
