/**
 * Skill Conformance Tests — backend-api
 * Skill reference: core/skills/backend-api/SKILL.md
 *
 * PURPOSE
 * -------
 * Proves that code generated by following the backend-api skill satisfies
 * the skill's documented contracts rule by rule.
 *
 * Each `describe` block maps to a specific Skill Rule (SR-*) documented in
 * the skill. When a test fails, it means either:
 *   (a) the generated code does not follow the skill — the fixture needs updating, OR
 *   (b) the skill documents a pattern that doesn't hold in practice — the skill
 *       needs updating.
 *
 * FIXTURES
 * --------
 *   UpdateProjectStatus.ts — ObjectAction with typed @DataModel params class,
 *                            canExecute guard, api: 'gql', returns: Project.
 *                            Covers SR-1 (Action decorator with params/returns),
 *                            SR-2 (ObjectAction base class + BaseDataModel params),
 *                            SR-3 (canExecute signature + execute).
 *
 *   GetProjectStatistics.ts — ModelAction with dedicated @DataModel result class,
 *                             type: 'read', no params (void).
 *                             Covers SR-1 (result class is @DataModel), SR-2
 *                             (ModelAction base class), SR-3 (execute shape).
 *
 *   InitializeProject.ts — ObjectAction with transactional: true, canExecute,
 *                          demonstrates multi-write safety pattern.
 *                          Covers SR-3 (transactional declaration, canExecute
 *                          returns string message for guard).
 *
 * KNOWN GAP (ExpectedError union returns)
 * -------
 *   The skill documents: "Return ExpectedError values for predictable business
 *   failures; do not throw them" and "returns: [SuccessClass, ErrorClass]" for
 *   typed union return types. No fixture in the current app uses ExpectedError.
 *   This gap is tracked in skill-scores.json and the SR-3 test for union returns
 *   is omitted. Adding a fixture with ExpectedError union returns would raise K
 *   and close the Correctness gap on that specific SR-3 rule.
 *
 * HOW TO RUN
 * ----------
 * From apps/project-management-app/backend/:
 *   TS_NODE_PROJECT=tsconfig.test.json npx jest --config config/jest.config.ts \
 *     --testPathPatterns='backend-api.skill-conformance' --no-coverage --verbose
 *
 * IMPORTANT: always pass --config config/jest.config.ts (ts-jest preset).
 */

import * as fs from 'fs';
import * as path from 'path';

// ─── Mock setup ────────────────────────────────────────────────────────────────
//
// Intercepts @drumr/framework-backend so @Action and @DataModel decorators can
// be observed without triggering DI registration or DB connections.
//
// capturedActions: Map<className, { options }> — populated as each action module
// loads and its @Action decorator fires.
//
// capturedModels: Map<className, { options }> — populated as @DataModel fires on
// params/result classes. These are the dedicated input/output model classes that
// the skill requires to be proper @DataModel classes (never inline plain objects).
//
// NOTE: jest.mock is hoisted to the top of the file at compile time. Keep all
// type annotations inside factories using `any` to avoid hoisting breakage.

jest.mock('@drumr/framework-backend', () => {
	class MockGlobalAction {}
	class MockModelAction {}
	class MockObjectAction {}
	class MockBaseDataModel {}

	const capturedActions: Map<string, { options: any }> = new Map();
	const capturedModels: Map<string, { options: any }> = new Map();

	function noop(..._args: any[]) {
		return (..._rest: any[]) => undefined;
	}

	function classPassThrough(_opts?: any) {
		return (cls: any) => cls;
	}

	const explicit: Record<string, any> = {
		_capturedActions: capturedActions,
		_capturedModels: capturedModels,
		GlobalAction: MockGlobalAction,
		ModelAction: MockModelAction,
		ObjectAction: MockObjectAction,
		BaseDataModel: MockBaseDataModel,
		// Captured decorator for actions.
		Action: (opts: any) => (cls: any) => {
			capturedActions.set(cls.name, { options: opts ?? {} });
			return cls;
		},
		// Captured decorator for params/result model classes.
		DataModel: (opts: any) => (cls: any) => {
			capturedModels.set(cls.name, { options: opts ?? {} });
			return cls;
		},
		Indexes: classPassThrough,
		Index: noop,
		Money: class {},
		WorkflowExecution: class {},
		WorkflowsManager: class {},
		Context: class {},
		logger: { info: noop(), warn: noop(), error: noop(), debug: noop() },
	};

	return new Proxy(explicit, {
		get: (target, prop: string) => (prop in target ? target[prop] : noop),
	});
});

// Stub transitive model dependencies so action fixtures can be loaded without
// any DB connections or circular evaluation.
jest.mock('../../../src/projects/data-models/project.data-model', () => ({
	Project: class Project {},
	ProjectStatus: {
		Planning: 'planning',
		Active: 'active',
		OnHold: 'on_hold',
		Completed: 'completed',
		Cancelled: 'cancelled',
	},
	ProjectPriority: {
		Low: 'low',
		Medium: 'medium',
		High: 'high',
		Critical: 'critical',
	},
}));
jest.mock('../../../src/tasks/data-models/task.data-model', () => ({
	Task: class Task {},
	TaskStatus: {
		ToDo: 'to_do',
		InProgress: 'in_progress',
		InReview: 'in_review',
		Done: 'done',
		Blocked: 'blocked',
	},
	TaskPriority: {
		Low: 'low',
		Medium: 'medium',
		High: 'high',
		Urgent: 'urgent',
		Critical: 'critical',
	},
}));
jest.mock('../../../src/config/data-sources/main/main.ds', () => ({
	MainDs: class MainDs {},
}));

import {
	GetProjectStatistics,
	ProjectStatisticsResult,
} from '../../../src/projects/actions/get-project-statistics.action';
import { InitializeProject } from '../../../src/projects/actions/initialize-project.action';
// Import action fixtures — each import triggers @Action and @DataModel decorators.
import {
	UpdateProjectStatus,
	UpdateProjectStatusParams,
} from '../../../src/projects/actions/update-project-status.action';

const mock = jest.requireMock('@drumr/framework-backend') as {
	_capturedActions: Map<string, { options: any }>;
	_capturedModels: Map<string, { options: any }>;
	GlobalAction: new () => object;
	ModelAction: new () => object;
	ObjectAction: new () => object;
	BaseDataModel: new () => object;
};

// ─── SR-1: Decorator contract ──────────────────────────────────────────────────
//
// Skill rules (backend-api/SKILL.md):
// "Configure crud.api: 'gql' in @DataModel() to expose CRUD operations via GraphQL."
// "For custom endpoints, always choose the correct base class: GlobalAction,
//  ModelAction, or ObjectAction."
// "Always declare params and returns in @Action(...) for robust type-safe generation."
// "Keep params as dedicated @DataModel() classes; avoid anonymous plain object contracts."
//
describe('SR-1 — API exposure decorator contracts', () => {
	describe('CRUD exposure: @DataModel with crud.api: gql', () => {
		const projectSource = fs.readFileSync(
			path.resolve(
				__dirname,
				'../../../src/projects/data-models/project.data-model.ts',
			),
			'utf8',
		);
		const taskSource = fs.readFileSync(
			path.resolve(
				__dirname,
				'../../../src/tasks/data-models/task.data-model.ts',
			),
			'utf8',
		);

		it('Project.ts declares crud: { api: "gql" } in @DataModel options', () => {
			// Skill: "Configure crud.api: 'gql' in @DataModel() to expose CRUD operations."
			// This is the primary pattern for exposing a model's CRUD through GraphQL.
			// A failure means the model's CRUD is not exposed via the framework convention.
			expect(projectSource).toMatch(/crud\s*:\s*\{[^}]*api\s*:\s*['"]gql['"]/s);
		});

		it('Task.ts declares crud: { api: "gql" } in @DataModel options', () => {
			// Same rule verified on a second model for Consistency.
			expect(taskSource).toMatch(/crud\s*:\s*\{[^}]*api\s*:\s*['"]gql['"]/s);
		});

		it('Project.ts declares crud.actions as an explicit array', () => {
			// Skill: "Prefer explicit crud.actions to keep API contracts stable and reviewable."
			// An explicit actions list prevents accidental exposure of new operations.
			expect(projectSource).toMatch(/actions\s*:\s*\[/);
		});
	});

	describe('@Action decorator — UpdateProjectStatus (ObjectAction, write, with params)', () => {
		const opts = () =>
			mock._capturedActions.get('UpdateProjectStatus')!.options;

		it('UpdateProjectStatus is decorated with @Action()', () => {
			// Skill: custom endpoints must use @Action — never manual GraphQL resolver wiring.
			expect(mock._capturedActions.has('UpdateProjectStatus')).toBe(true);
		});

		it('@Action declares api: "gql" (exposed in GraphQL schema)', () => {
			// Skill: "@Action({ api: 'gql' })" is required to include the action in the schema.
			// A failure means the action is not reachable via GraphQL.
			expect(opts().api).toBe('gql');
		});

		it('@Action declares type: "write"', () => {
			// Skill: type is required on all actions; 'write' for mutations.
			expect(opts().type).toBe('write');
		});

		it('@Action declares params: a class reference (not inline object)', () => {
			// Skill: "Keep params as dedicated @DataModel() classes; avoid anonymous plain object contracts."
			// A class reference as params enables schema introspection and field-level validation.
			expect(opts().params).toBeDefined();
			expect(typeof opts().params).toBe('function');
		});

		it('@Action declares returns: a class reference', () => {
			// Skill: "Always declare returns in @Action(...) for robust type-safe generation."
			expect(opts().returns).toBeDefined();
		});

		it('@Action declares model: a class reference (ObjectAction targets a model)', () => {
			// Skill: ObjectAction is "tied to a specific model instance" — model must be declared.
			expect(opts().model).toBeDefined();
			expect(typeof opts().model).toBe('function');
		});
	});

	describe('@Action decorator — GetProjectStatistics (ModelAction, read, no params)', () => {
		const opts = () =>
			mock._capturedActions.get('GetProjectStatistics')!.options;

		it('GetProjectStatistics is decorated with @Action()', () => {
			expect(mock._capturedActions.has('GetProjectStatistics')).toBe(true);
		});

		it('@Action declares api: "gql"', () => {
			expect(opts().api).toBe('gql');
		});

		it('@Action declares type: "read"', () => {
			// Skill: 'read' for query operations that do not mutate state.
			expect(opts().type).toBe('read');
		});

		it('@Action declares returns: ProjectStatisticsResult (not void)', () => {
			// Skill: always declare returns so the GraphQL union types are explicit.
			expect(opts().returns).toBeDefined();
		});
	});

	describe('@Action decorator — InitializeProject (ObjectAction, transactional: true)', () => {
		const opts = () => mock._capturedActions.get('InitializeProject')!.options;

		it('InitializeProject is decorated with @Action()', () => {
			expect(mock._capturedActions.has('InitializeProject')).toBe(true);
		});

		it('@Action declares transactional: true for multi-write consistency', () => {
			// Skill: "Use transactional: true for multi-write consistency in one action execution."
			// InitializeProject saves both a project status change and a new Task atomically.
			expect(opts().transactional).toBe(true);
		});
	});

	describe('params class is a @DataModel() class (UpdateProjectStatusParams)', () => {
		it('UpdateProjectStatusParams is decorated with @DataModel()', () => {
			// Skill: "Keep params as dedicated @DataModel() classes; avoid anonymous plain object contracts."
			// The params class must be registered as a DataModel so the framework can
			// introspect its fields and generate the correct GraphQL input type.
			expect(mock._capturedModels.has('UpdateProjectStatusParams')).toBe(true);
		});

		it('InitializeProjectParams is decorated with @DataModel()', () => {
			// Same rule on a second params class.
			expect(mock._capturedModels.has('InitializeProjectParams')).toBe(true);
		});
	});

	describe('result class is a @DataModel() class (ProjectStatisticsResult)', () => {
		it('ProjectStatisticsResult is decorated with @DataModel()', () => {
			// Skill: returns class must be a @DataModel() for the framework to generate
			// the GraphQL object type. A plain object return type breaks schema generation.
			expect(mock._capturedModels.has('ProjectStatisticsResult')).toBe(true);
		});
	});
});

// ─── SR-2: Base class contract ────────────────────────────────────────────────
//
// Skill rule (backend-api/SKILL.md):
// "For custom endpoints, always choose the correct base class:
//  GlobalAction, ModelAction, or ObjectAction."
// Params and result classes extend BaseDataModel.
//
describe('SR-2 — correct base class per action type', () => {
	it('UpdateProjectStatus extends ObjectAction via prototype chain', () => {
		// Skill: ObjectAction is for actions "tied to a specific model instance".
		// Using the wrong base class removes canExecute(instance) availability.
		expect(UpdateProjectStatus.prototype).toBeInstanceOf(mock.ObjectAction);
	});

	it('GetProjectStatistics extends ModelAction via prototype chain', () => {
		// Skill: ModelAction is for actions "tied to a model class/collection".
		// It operates across all instances of a model, not a single record.
		expect(GetProjectStatistics.prototype).toBeInstanceOf(mock.ModelAction);
	});

	it('InitializeProject extends ObjectAction via prototype chain', () => {
		expect(InitializeProject.prototype).toBeInstanceOf(mock.ObjectAction);
	});

	it('UpdateProjectStatusParams extends BaseDataModel via prototype chain', () => {
		// Skill: params class must extend BaseDataModel (it is a @DataModel class).
		// A plain class as params breaks field-level validation and schema introspection.
		expect(UpdateProjectStatusParams.prototype).toBeInstanceOf(
			mock.BaseDataModel,
		);
	});

	it('ProjectStatisticsResult extends BaseDataModel via prototype chain', () => {
		// Same rule: result classes are @DataModel classes and must extend BaseDataModel.
		expect(ProjectStatisticsResult.prototype).toBeInstanceOf(
			mock.BaseDataModel,
		);
	});
});

// ─── SR-3: Behavioral contracts ───────────────────────────────────────────────
//
// Skill rules (backend-api/SKILL.md):
// "Use canExecute for early business guards and user-friendly blockage reasons."
// "canExecute returns Promise<boolean | string> — string message is the blockage reason."
// "Return true to allow, a string reason to block."
// "Use transactional: true for multi-write consistency in one action execution."
// "Return ExpectedError values for predictable business failures; do not throw them."
//   GAP: current app has no ExpectedError fixture — test omitted, tracked in scores.
//
describe('SR-3 — behavioral and structural rules', () => {
	const updateStatusSource = fs.readFileSync(
		path.resolve(
			__dirname,
			'../../../src/projects/actions/update-project-status.action.ts',
		),
		'utf8',
	);
	const initProjectSource = fs.readFileSync(
		path.resolve(
			__dirname,
			'../../../src/projects/actions/initialize-project.action.ts',
		),
		'utf8',
	);
	const getStatisticsSource = fs.readFileSync(
		path.resolve(
			__dirname,
			'../../../src/projects/actions/get-project-statistics.action.ts',
		),
		'utf8',
	);

	describe('canExecute signature and return patterns', () => {
		it('UpdateProjectStatus.canExecute is declared with Promise<boolean | string> return type', () => {
			// Skill: canExecute is the early business guard — its return type must be
			// Promise<boolean | string> to support both allow (true) and block (string) outcomes.
			expect(updateStatusSource).toMatch(
				/canExecute[^)]*\)\s*:\s*Promise<boolean\s*\|\s*string>/,
			);
		});

		it('UpdateProjectStatus.canExecute returns a string message when blocking', () => {
			// Skill: "Use canExecute for early business guards and user-friendly blockage reasons."
			// A string return provides the human-readable reason shown to the user.
			expect(updateStatusSource).toMatch(/return\s*['"][^'"]+['"]/);
		});

		it('UpdateProjectStatus.canExecute returns true for the happy path', () => {
			// Skill: "Return true to allow execution" — this is the happy-path guard pattern.
			expect(updateStatusSource).toMatch(/return\s+true\s*;/);
		});

		it('InitializeProject.canExecute is declared with Promise<boolean | string> return type', () => {
			expect(initProjectSource).toMatch(
				/canExecute[^)]*\)\s*:\s*Promise<boolean\s*\|\s*string>/,
			);
		});
	});

	describe('execute() signature', () => {
		it('UpdateProjectStatus.execute is declared as a protected/override async method', () => {
			// Skill: execute() is the main business logic method — must be async.
			expect(updateStatusSource).toMatch(
				/(?:override\s+)?async\s+execute\s*\(/,
			);
		});

		it('GetProjectStatistics.execute is declared as a protected async method', () => {
			expect(getStatisticsSource).toMatch(
				/(?:protected\s+)?async\s+execute\s*\(/,
			);
		});

		it('GetProjectStatistics.execute returns Promise<ProjectStatisticsResult>', () => {
			// Skill: always declare a typed return type on execute() for schema generation.
			expect(getStatisticsSource).toMatch(/Promise<ProjectStatisticsResult>/);
		});
	});

	describe('transactional pattern', () => {
		it('InitializeProject uses transactional: true for multi-write atomicity', () => {
			// Skill: "Use transactional: true for multi-write consistency in one action execution."
			// InitializeProject saves both a project status and a new Task — both must
			// succeed or both must roll back. transactional: true enforces this declaratively.
			expect(initProjectSource).toMatch(/transactional\s*:\s*true/);
		});

		it('transactional: true is declared in @Action options (not in execute() body)', () => {
			// Skill: transaction wrapping is configured declaratively via the @Action decorator,
			// not by manually calling db.transaction() inside execute().
			expect(
				mock._capturedActions.get('InitializeProject')!.options.transactional,
			).toBe(true);
		});
	});

	describe('params declared as @DataModel class (not inline object)', () => {
		it('UpdateProjectStatusParams is a named exported class (not an inline literal)', () => {
			// Skill: "Keep params as dedicated @DataModel() classes; avoid anonymous plain object contracts."
			// A dedicated class enables field decorators, validation, and proper GraphQL input type generation.
			expect(updateStatusSource).toMatch(
				/export\s+class\s+UpdateProjectStatusParams/,
			);
		});
	});
});

// ─── SR-4: Forbidden imports — individual + adversarial repo-wide scan ────────
//
// Skill rules (backend-api/SKILL.md):
// "Prefer @DataModel({ crud: { api: 'gql' } }) for CRUD exposure;
//  avoid manual resolver coding in app code."
// All API and action imports must come from @drumr/framework-backend exclusively.
// Direct imports from @apollo/server, @pothos/core, or graphql are internal
// framework concerns — app code must never reference them directly.
//
describe('SR-4 — action source files do not import from raw API stack libraries', () => {
	describe('individual fixture checks', () => {
		const updateStatusSource = fs.readFileSync(
			path.resolve(
				__dirname,
				'../../../src/projects/actions/update-project-status.action.ts',
			),
			'utf8',
		);
		const getStatisticsSource = fs.readFileSync(
			path.resolve(
				__dirname,
				'../../../src/projects/actions/get-project-statistics.action.ts',
			),
			'utf8',
		);
		const initProjectSource = fs.readFileSync(
			path.resolve(
				__dirname,
				'../../../src/projects/actions/initialize-project.action.ts',
			),
			'utf8',
		);

		it('UpdateProjectStatus.ts does not import from "@apollo/server"', () => {
			// Skill: manual Apollo resolver wiring is forbidden in app action code.
			expect(updateStatusSource).not.toMatch(/from ['"]@apollo\/server['"]/);
		});

		it('UpdateProjectStatus.ts does not import from "@pothos/core"', () => {
			// Skill: Pothos schema builder is a framework-internal concern.
			expect(updateStatusSource).not.toMatch(/from ['"]@pothos\/core['"]/);
		});

		it('UpdateProjectStatus.ts does not import from "graphql" directly', () => {
			// Skill: raw graphql package imports indicate manual schema wiring, which the
			// framework handles automatically via @DataModel and @Action declarations.
			expect(updateStatusSource).not.toMatch(/from ['"]graphql['"]/);
		});

		it('UpdateProjectStatus.ts imports all framework symbols from "@drumr/framework-backend"', () => {
			// Skill: all framework imports must come from the single @drumr/framework-backend entry point.
			expect(updateStatusSource).toMatch(
				/from ['"]@drumr\/framework-backend['"]/,
			);
		});

		it('GetProjectStatistics.ts does not import from "@apollo/server" or "@pothos/core"', () => {
			expect(getStatisticsSource).not.toMatch(/from ['"]@apollo\/server['"]/);
			expect(getStatisticsSource).not.toMatch(/from ['"]@pothos\/core['"]/);
		});

		it('GetProjectStatistics.ts imports from "@drumr/framework-backend"', () => {
			expect(getStatisticsSource).toMatch(
				/from ['"]@drumr\/framework-backend['"]/,
			);
		});

		it('InitializeProject.ts does not import from raw API stack libraries', () => {
			expect(initProjectSource).not.toMatch(/from ['"]@apollo\/server['"]/);
			expect(initProjectSource).not.toMatch(/from ['"]@pothos\/core['"]/);
			expect(initProjectSource).not.toMatch(/from ['"]graphql['"]/);
		});

		it('InitializeProject.ts imports from "@drumr/framework-backend"', () => {
			expect(initProjectSource).toMatch(
				/from ['"]@drumr\/framework-backend['"]/,
			);
		});
	});

	describe('adversarial repo-wide scan — all action files', () => {
		const srcRoot = path.resolve(__dirname, '../../../src');

		function collectActionSources(
			dir: string,
		): Array<{ file: string; source: string }> {
			const results: Array<{ file: string; source: string }> = [];
			for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
				const fullPath = path.join(dir, entry.name);
				if (entry.isDirectory()) {
					results.push(...collectActionSources(fullPath));
				} else if (
					entry.name.endsWith('.ts') &&
					!entry.name.endsWith('.d.ts')
				) {
					results.push({
						file: entry.name,
						source: fs.readFileSync(fullPath, 'utf8'),
					});
				}
			}
			return results;
		}

		const allActionSources: Array<{ file: string; source: string }> = [];
		for (const mod of fs.readdirSync(srcRoot)) {
			const actionsDir = path.join(srcRoot, mod, 'actions');
			if (fs.existsSync(actionsDir) && fs.statSync(actionsDir).isDirectory()) {
				allActionSources.push(...collectActionSources(actionsDir));
			}
		}

		it('no action file imports from "@apollo/server"', () => {
			// Adversarial: any action file importing @apollo/server indicates manual resolver
			// construction, which violates the skill's fundamental "no manual resolver coding" rule.
			const violations = allActionSources.filter((f) =>
				/from ['"]@apollo\/server['"]/.test(f.source),
			);
			expect(violations.map((f) => f.file)).toHaveLength(0);
		});

		it('no action file imports from "@pothos/core"', () => {
			// Adversarial: Pothos schema builder must not appear in app action code.
			const violations = allActionSources.filter((f) =>
				/from ['"]@pothos\/core['"]/.test(f.source),
			);
			expect(violations.map((f) => f.file)).toHaveLength(0);
		});

		it('no action file imports from "graphql" directly', () => {
			// Adversarial: raw graphql package in action files indicates manual schema wiring.
			const violations = allActionSources.filter((f) =>
				/from ['"]graphql['"]/.test(f.source),
			);
			expect(violations.map((f) => f.file)).toHaveLength(0);
		});
	});
});
