/**
 * Skill Conformance Tests — backend-app
 * Skill reference: core/skills/backend-app/SKILL.md
 *
 * PURPOSE
 * -------
 * Proves that code generated by following the backend-app skill satisfies the
 * skill's documented contracts rule by rule.
 *
 * Each `describe` block maps to a specific Skill Rule (SR-*) documented in
 * the skill. When a test fails, it means either:
 *   (a) the generated code does not follow the skill — the fixture needs updating, OR
 *   (b) the skill documents a pattern that doesn't hold in practice — the skill
 *       needs updating.
 *
 * FIXTURES
 * --------
 *   App.ts  — source text only (fs.readFileSync).
 *             Backend Jest has no need to live-import the app class because
 *             @App() triggers full framework boot. All SR-* contracts are
 *             fully verifiable from source text (import declarations, class
 *             shape, decorator presence, lifecycle hook signatures).
 *
 * SkillScore (initial):
 *   C=3 (SR-1+SR-2+SR-3 all covered)
 *   K=3 (one fixture; App.ts is the only bootstrap file — K capped at 3 per rules)
 *   D=3 (structural invariant)
 *   R=2 (SR-4 + adversarial repo-wide scan for banned manual initializations)
 *   Score = (3×0.40 + 3×0.20 + 3×0.20 + 2×0.20) × 33.33 = 93.3
 *
 * HOW TO RUN
 * ----------
 * From apps/project-management-app/backend/:
 *   TS_NODE_PROJECT=tsconfig.test.json npx jest --config config/jest.config.ts \
 *     --testPathPatterns='backend-app.skill-conformance' --no-coverage --verbose
 *
 * IMPORTANT: always pass --config config/jest.config.ts (ts-jest preset).
 */

import * as fs from 'fs';
import * as path from 'path';

// ─── Fixture loading ───────────────────────────────────────────────────────────
//
// __dirname = apps/project-management-app/backend/tests/unit/skill-conformance
// SRC_ROOT  = apps/project-management-app/backend/src
// APP_ROOT  = apps/project-management-app  (for cross-package adversarial scan)

const SRC_ROOT = path.resolve(__dirname, '../../../src');
const APP_ROOT = path.resolve(__dirname, '../../..');

const appSrc = fs.readFileSync(path.join(SRC_ROOT, 'App.ts'), 'utf-8');

// ─── SR-1: Import / decorator contracts ───────────────────────────────────────

describe('SR-1: Import and decorator contracts', () => {
	// Rule: "Import from @drumr/framework-backend"
	it('App.ts: imports App and BaseApp from @drumr/framework-backend', () => {
		expect(appSrc).toMatch(/from\s+['"]@drumr\/framework-backend['"]/);
		expect(appSrc).toMatch(/\bApp\b/);
		expect(appSrc).toMatch(/\bBaseApp\b/);
	});

	// Rule: "@App() decorator applied to the class"
	it('App.ts: @App() decorator is applied', () => {
		expect(appSrc).toMatch(/@App\s*\(\s*\)/);
	});

	// Rule: "side-effect imports for files that register framework metadata"
	it('App.ts: permissions are registered via .perm.ts files (auto-loaded by convention)', () => {
		// In the module-based structure, .perm.ts files under config/auth/ are
		// auto-loaded by the framework — no explicit side-effect import needed in App.ts.
		const permFile = path.join(SRC_ROOT, 'config', 'auth', 'admin.perm.ts');
		expect(fs.existsSync(permFile)).toBe(true);
	});
});

// ─── SR-2: Structural / base-class contracts ──────────────────────────────────

describe('SR-2: Structural contracts', () => {
	// Rule: "The class must extend BaseApp"
	it('App.ts: app class extends BaseApp', () => {
		expect(appSrc).toMatch(/class\s+\w+\s+extends\s+BaseApp/);
	});

	// Rule: "Keep exactly one @App() class per backend runtime app"
	it('App.ts: exactly one @App() decorator in the file', () => {
		const matches = appSrc.match(/@App\s*\(\s*\)/g) ?? [];
		expect(matches.length).toBe(1);
	});

	// Rule: "constructor injection is preferred"
	it('App.ts: constructor calls super()', () => {
		expect(appSrc).toMatch(/super\s*\(\s*\)/);
	});
});

// ─── SR-3: Behavioral guarantees ─────────────────────────────────────────────

describe('SR-3: Behavioral guarantees', () => {
	// Rule: "beforeStart() — register service/datasource overrides"
	it('App.ts: beforeStart() lifecycle hook declared with override keyword', () => {
		expect(appSrc).toMatch(/override\s+(?:async\s+)?beforeStart\s*\(/);
	});

	// Rule: "this.register(...) in beforeStart()"
	it('App.ts: this.register() call is inside the file (service override)', () => {
		expect(appSrc).toMatch(/this\.register\s*\(/);
	});

	// Rule: "afterStart() — startup logs, warmup after infrastructure is up"
	it('App.ts: afterStart() lifecycle hook declared with override keyword', () => {
		expect(appSrc).toMatch(/override\s+(?:async\s+)?afterStart\s*\(/);
	});

	// Rule: "beforeStop() — graceful shutdown work"
	it('App.ts: beforeStop() lifecycle hook declared with override keyword', () => {
		expect(appSrc).toMatch(/override\s+(?:async\s+)?beforeStop\s*\(/);
	});

	// Rule: "onError(error) — error reporting and diagnostics"
	it('App.ts: onError() lifecycle hook declared with override keyword', () => {
		expect(appSrc).toMatch(/override\s+(?:async\s+)?onError\s*\(/);
	});

	// Rule: "Use App.resolve(Token) in afterStart(), not in constructor, when
	//        override-sensitive dependencies must be resolved after beforeStart"
	it('App.ts: App.resolve() used in afterStart/beforeStop/onError (not just constructor)', () => {
		// The app uses App.resolve in afterStart or later hooks — verify it exists somewhere
		// outside the constructor (constructor is before beforeStart runs)
		const afterStartBlock =
			appSrc.match(
				/override\s+(?:async\s+)?afterStart[\s\S]*?(?=override\s+(?:async\s+)?\w|$)/,
			)?.[0] ?? '';
		const beforeStopBlock =
			appSrc.match(
				/override\s+(?:async\s+)?beforeStop[\s\S]*?(?=override\s+(?:async\s+)?\w|$)/,
			)?.[0] ?? '';
		const onErrorBlock =
			appSrc.match(
				/override\s+(?:async\s+)?onError[\s\S]*?(?=override\s+(?:async\s+)?\w|$)/,
			)?.[0] ?? '';
		// App.resolve may not be used in every app — only assert if it appears at all
		// If App.resolve is present in the file, it must NOT appear only inside the constructor
		if (appSrc.includes('App.resolve')) {
			const constructorBlock =
				appSrc.match(
					/constructor\s*\([\s\S]*?\)\s*\{[\s\S]*?super\s*\(\s*\)\s*;?[\s\S]*?\}/,
				)?.[0] ?? '';
			const resolveInConstructorOnly =
				constructorBlock.includes('App.resolve') &&
				!afterStartBlock.includes('App.resolve') &&
				!beforeStopBlock.includes('App.resolve') &&
				!onErrorBlock.includes('App.resolve');
			expect(resolveInConstructorOnly).toBe(false);
		}
	});

	// Rule: "ConfigService injected via constructor to read config/config.json values"
	it('App.ts: ConfigService is constructor-injected', () => {
		expect(appSrc).toMatch(/ConfigService/);
		// ConfigService appears as a constructor parameter type
		expect(appSrc).toMatch(/constructor\s*\([\s\S]*?ConfigService[\s\S]*?\)/);
	});
});

// ─── SR-4: Forbidden patterns + adversarial scan ─────────────────────────────

describe('SR-4: Forbidden patterns', () => {
	// Rule: "Do not manually initialize Express, Apollo, TypeORM, DBOS, or auth routes"
	it('App.ts: does not manually create an Express app', () => {
		expect(appSrc).not.toMatch(/express\s*\(\s*\)/);
		expect(appSrc).not.toMatch(/new\s+Express/);
	});

	it('App.ts: does not manually instantiate ApolloServer', () => {
		expect(appSrc).not.toMatch(/new\s+ApolloServer/);
	});

	it('App.ts: does not manually call DataSource constructor (TypeORM)', () => {
		expect(appSrc).not.toMatch(/new\s+DataSource\s*\(/);
	});

	// Rule: "Do not put service overrides in afterStart()"
	it('App.ts: this.register() does not appear inside afterStart()', () => {
		const afterStartBlock =
			appSrc.match(
				/override\s+(?:async\s+)?afterStart\s*\([^)]*\)\s*(?::\s*\S+\s*)?\{[\s\S]*?\n\s*\}/,
			)?.[0] ?? '';
		expect(afterStartBlock).not.toMatch(/this\.register\s*\(/);
	});

	// Rule: "Do not invent lifecycle hooks beyond the four documented ones"
	it('App.ts: only uses documented lifecycle hook names', () => {
		const hookPattern = /override\s+(?:async\s+)?(\w+)\s*\(/g;
		const knownHooks = new Set([
			'beforeStart',
			'afterStart',
			'beforeStop',
			'onError',
			'constructor',
		]);
		let match: RegExpExecArray | null = hookPattern.exec(appSrc);
		while (match !== null) {
			expect(knownHooks.has(match[1])).toBe(true);
			match = hookPattern.exec(appSrc);
		}
	});

	// Adversarial: scan backend/src/ to ensure no other file imports express() directly
	// (app code should never manually wire up Express — that's the framework's job)
	it('adversarial: no backend src file manually requires/imports express directly', () => {
		const EXCLUDED = new Set(['node_modules']);

		function collectTs(dir: string): string[] {
			const results: string[] = [];
			for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
				if (EXCLUDED.has(entry.name)) continue;
				const full = path.join(dir, entry.name);
				if (entry.isDirectory()) results.push(...collectTs(full));
				else if (entry.name.endsWith('.ts')) results.push(full);
			}
			return results;
		}

		const violations: string[] = [];
		for (const file of collectTs(SRC_ROOT)) {
			const src = fs.readFileSync(file, 'utf-8');
			if (
				src.match(/express\s*\(\s*\)/) ||
				src.match(/new\s+ApolloServer\s*\(/)
			) {
				violations.push(path.relative(APP_ROOT, file));
			}
		}
		expect(violations).toEqual([]);
	});

	// Adversarial: App.ts must NOT import directly from internal framework paths
	it('App.ts: does not import from internal core/ paths', () => {
		expect(appSrc).not.toMatch(/from\s+['"].*\/core\/backend\//);
		expect(appSrc).not.toMatch(/from\s+['"].*\/core\/src\//);
	});
});
