/**
 * Skill Conformance Tests — backend-workflows
 * Skill reference: core/skills/backend-workflows/SKILL.md
 *
 * PURPOSE
 * -------
 * Proves that code generated by following the backend-workflows skill satisfies
 * the skill's documented contracts rule by rule.
 *
 * Each `describe` block maps to a specific Skill Rule (SR-*) documented in
 * the skill. When a test fails, it means either:
 *   (a) the generated code does not follow the skill — the fixture needs updating, OR
 *   (b) the skill documents a pattern that doesn't hold in practice — the skill
 *       needs updating.
 *
 * FIXTURES
 * --------
 *   SyncDataWorkflow.ts              — queue-backed BaseWorkflow, no constructor args,
 *                                      @Step decorators, reportProgress at 33/66/100
 *   ArchiveProjectWorkflow.ts        — plain BaseWorkflow, constructor injection,
 *                                      callSubworkflow, multiple @Step methods
 *   DailyInactiveTasksCleanupWorkflow.ts — BaseScheduledWorkflow, cron schedule,
 *                                          constructor injection
 *
 * Three fixtures (two workflow base-class types) raise Consistency above the
 * single-fixture baseline and cover SR-2 for both BaseWorkflow and
 * BaseScheduledWorkflow.
 *
 * HOW TO RUN
 * ----------
 * From apps/project-management-app/backend/:
 *   TS_NODE_PROJECT=tsconfig.test.json npx jest --config config/jest.config.ts \
 *     --testPathPatterns='backend-workflows.skill-conformance' --no-coverage --verbose
 *
 * IMPORTANT: always pass --config config/jest.config.ts (ts-jest preset).
 */

import * as fs from 'fs';
import * as path from 'path';

// ─── Mock setup ────────────────────────────────────────────────────────────────
//
// Intercepts @drumr/framework-backend so the @Workflow and @Step decorators
// can be observed without triggering real DBOS/queue infrastructure.
//
// capturedWorkflows: Map<className, { options }> — populated when each workflow
// module is loaded and its @Workflow decorator executes.
//
// capturedSteps: Map<className, Set<methodName>> — populated when each @Step
// decorator executes on a method.
//
// NOTE: jest.mock is hoisted to the top of the file at compile time.

jest.mock('@drumr/framework-backend', () => {
	class MockBaseWorkflow {}
	class MockBaseScheduledWorkflow {}
	class MockBaseDataModel {}

	const capturedWorkflows: Map<string, { options: any }> = new Map();
	const capturedSteps: Map<string, Set<string>> = new Map();

	function noop(..._args: any[]) {
		return (..._rest: any[]) => undefined;
	}

	function classPassThrough(_opts?: any) {
		return (cls: any) => cls;
	}

	const explicit: Record<string, any> = {
		_capturedWorkflows: capturedWorkflows,
		_capturedSteps: capturedSteps,
		BaseWorkflow: MockBaseWorkflow,
		BaseScheduledWorkflow: MockBaseScheduledWorkflow,
		BaseDataModel: MockBaseDataModel,

		// Captures @Workflow({ queue?, schedule?, ... }) on each workflow class.
		Workflow: (opts?: any) => (cls: any) => {
			capturedWorkflows.set(cls.name, { options: opts ?? {} });
			return cls;
		},

		// Captures @Step({ retries?, ... }) on individual methods.
		// Property decorators receive (target, propertyKey) — we record the
		// class name (target.constructor.name) + method name.
		Step: (opts?: any) => (target: any, propertyKey: string) => {
			const className: string = target?.constructor?.name ?? 'unknown';
			if (!capturedSteps.has(className)) {
				capturedSteps.set(className, new Set());
			}
			capturedSteps.get(className)!.add(propertyKey);
		},

		// Pass-throughs — referenced by DailyInactiveTasksCleanupWorkflow's result model.
		DataModel: classPassThrough,
		Indexes: classPassThrough,
	};

	return new Proxy(explicit, {
		get: (target, prop: string) => (prop in target ? target[prop] : noop),
	});
});

// Stub internal dependencies to prevent DB / infrastructure connections.
jest.mock('../../../src/config/data-sources/main/main.ds', () => ({
	MainDs: class MainDs {},
}));
jest.mock('../../../src/global/services/activity-log.service', () => ({
	ActivityLogService: class ActivityLogService {},
}));
jest.mock('../../../src/global/workflows/notify-stakeholders.workflow', () => ({
	NotifyStakeholdersWorkflow: class NotifyStakeholdersWorkflow {},
}));
jest.mock('../../../src/tasks/data-models/task.data-model', () => ({
	Task: class Task {},
	TaskStatus: { Blocked: 'blocked', Active: 'active' },
}));
jest.mock('../../../src/projects/data-models/project.data-model', () => ({
	Project: class Project {},
	ProjectStatus: { Active: 'active', Archived: 'archived' },
}));

import { DailyInactiveTasksCleanupWorkflow } from '../../../src/global/workflows/scheduled/daily-inactive-tasks-cleanup.workflow';
import { SyncDataWorkflow } from '../../../src/global/workflows/sync-data.workflow';
import { ArchiveProjectWorkflow } from '../../../src/projects/workflows/archive-project.workflow';

const mock = jest.requireMock('@drumr/framework-backend') as {
	_capturedWorkflows: Map<string, { options: any }>;
	_capturedSteps: Map<string, Set<string>>;
	BaseWorkflow: new () => object;
	BaseScheduledWorkflow: new () => object;
};

// ─── SR-1: @Workflow() decorator contract ──────────────────────────────────────
//
// Skill rule (backend-workflows/SKILL.md):
// "Define workflows as classes decorated with @Workflow(...) and extending BaseWorkflow."
// "@Workflow options: queue, timeout, priority, schedule"
// "schedule: for scheduled workflows — cron + timezone required"
//
describe('SR-1 — @Workflow() decorator is used with required options', () => {
	describe('SyncDataWorkflow — queue-backed BaseWorkflow', () => {
		it('class is decorated with @Workflow()', () => {
			// Without @Workflow the DBOS runtime will not register the class —
			// silent omission that only surfaces at execution time.
			expect(mock._capturedWorkflows.has('SyncDataWorkflow')).toBe(true);
		});

		it('@Workflow() declares a queue option', () => {
			// Skill: "queue: queue class or queue name" — assigned queue controls
			// concurrency and retry policy for this workflow.
			const opts = mock._capturedWorkflows.get('SyncDataWorkflow')!.options;
			expect(opts.queue).toBeDefined();
		});
	});

	describe('ArchiveProjectWorkflow — plain BaseWorkflow (default queue)', () => {
		it('class is decorated with @Workflow()', () => {
			expect(mock._capturedWorkflows.has('ArchiveProjectWorkflow')).toBe(true);
		});

		it('@Workflow() options object is defined (may omit queue for default)', () => {
			// Skill allows omitting queue to use the default queue.
			// The decorator itself must still be present.
			const opts = mock._capturedWorkflows.get(
				'ArchiveProjectWorkflow',
			)!.options;
			expect(opts).toBeDefined();
		});
	});

	describe('DailyInactiveTasksCleanupWorkflow — BaseScheduledWorkflow', () => {
		it('class is decorated with @Workflow()', () => {
			expect(
				mock._capturedWorkflows.has('DailyInactiveTasksCleanupWorkflow'),
			).toBe(true);
		});

		it('@Workflow() declares a schedule option', () => {
			// Skill: "schedule: for scheduled workflows (cron + timezone) — required"
			const opts = mock._capturedWorkflows.get(
				'DailyInactiveTasksCleanupWorkflow',
			)!.options;
			expect(opts.schedule).toBeDefined();
		});

		it('@Workflow().schedule has a cron string', () => {
			// Skill: "Scheduling uses valid cron and timezone when present."
			const opts = mock._capturedWorkflows.get(
				'DailyInactiveTasksCleanupWorkflow',
			)!.options;
			expect(typeof opts.schedule.cron).toBe('string');
			expect(opts.schedule.cron.length).toBeGreaterThan(0);
		});

		it('@Workflow().schedule has a timezone string', () => {
			// Skill pitfall: "Adding non-idempotent side effects" — bad; missing timezone — bad.
			const opts = mock._capturedWorkflows.get(
				'DailyInactiveTasksCleanupWorkflow',
			)!.options;
			expect(typeof opts.schedule.timezone).toBe('string');
			expect(opts.schedule.timezone.length).toBeGreaterThan(0);
		});
	});
});

// ─── SR-2: Base class contract ──────────────────────────────────────────────────
//
// Skill rule (backend-workflows/SKILL.md):
// "BaseWorkflow  — event-driven async workflows"
// "BaseScheduledWorkflow — time-driven, requires cron + timezone"
//
// Using the wrong base class silently breaks the execution contract:
// BaseScheduledWorkflow.execute() accepts no params; BaseWorkflow.execute() does.
//
describe('SR-2 — workflow class extends the correct framework base class', () => {
	it('SyncDataWorkflow extends BaseWorkflow via prototype chain', () => {
		expect(SyncDataWorkflow.prototype).toBeInstanceOf(mock.BaseWorkflow);
	});

	it('ArchiveProjectWorkflow extends BaseWorkflow via prototype chain', () => {
		expect(ArchiveProjectWorkflow.prototype).toBeInstanceOf(mock.BaseWorkflow);
	});

	it('DailyInactiveTasksCleanupWorkflow extends BaseScheduledWorkflow via prototype chain', () => {
		expect(DailyInactiveTasksCleanupWorkflow.prototype).toBeInstanceOf(
			mock.BaseScheduledWorkflow,
		);
	});

	it('DailyInactiveTasksCleanupWorkflow does NOT extend plain BaseWorkflow', () => {
		// A scheduled workflow that extends BaseWorkflow would not be registered
		// as a cron trigger by the DBOS scheduler.
		expect(DailyInactiveTasksCleanupWorkflow.prototype).not.toBeInstanceOf(
			mock.BaseWorkflow,
		);
	});
});

// ─── SR-3: Behavioral contracts ────────────────────────────────────────────────
//
// Skill rule (backend-workflows/SKILL.md):
// "Use @Step for checkpointed units of work."
// "In execute(), call each step using this.callStep(...)."
// "Calling step methods directly instead of this.callStep(...) — [forbidden pitfall]"
// "execute() exists and is async."
// "reportProgress(0-100) at meaningful milestones."
//
describe('SR-3 — execute() and @Step contracts', () => {
	describe('SyncDataWorkflow', () => {
		it('execute() method exists on the prototype', () => {
			expect(typeof SyncDataWorkflow.prototype.execute).toBe('function');
		});

		it('execute() is async (returns a Promise)', async () => {
			// Workflow execute() must be async — DBOS will await it.
			// We instantiate with empty mock deps and call execute with no args.
			const instance = new SyncDataWorkflow();

			// Patch callStep and reportProgress so the method body completes without real DBOS.
			(instance as any).callStep = jest.fn().mockResolvedValue('ok');
			(instance as any).reportProgress = jest.fn().mockResolvedValue(undefined);

			const result = instance.execute();
			expect(result).toBeInstanceOf(Promise);
			await result; // must not throw
		});

		it('@Step is applied to at least one method', () => {
			// Skill: "Use @Step for checkpointed units of work." — at least one step
			// must be decorated; a workflow with no steps has no durability guarantees.
			const steps = mock._capturedSteps.get('SyncDataWorkflow');
			expect(steps).toBeDefined();
			expect(steps!.size).toBeGreaterThan(0);
		});

		it('validateData, syncData, verifySync are all decorated with @Step', () => {
			// Each business unit in SyncDataWorkflow is a separate durable checkpoint.
			const steps = mock._capturedSteps.get('SyncDataWorkflow')!;
			expect(steps.has('validateData')).toBe(true);
			expect(steps.has('syncData')).toBe(true);
			expect(steps.has('verifySync')).toBe(true);
		});
	});

	describe('ArchiveProjectWorkflow', () => {
		it('execute() method exists on the prototype', () => {
			expect(typeof ArchiveProjectWorkflow.prototype.execute).toBe('function');
		});

		it('@Step is applied to at least one method', () => {
			const steps = mock._capturedSteps.get('ArchiveProjectWorkflow');
			expect(steps).toBeDefined();
			expect(steps!.size).toBeGreaterThan(0);
		});
	});

	describe('DailyInactiveTasksCleanupWorkflow', () => {
		it('execute() method exists on the prototype', () => {
			// BaseScheduledWorkflow.execute() takes no params — skill enforces this.
			expect(typeof DailyInactiveTasksCleanupWorkflow.prototype.execute).toBe(
				'function',
			);
		});
	});
});

// ─── SR-4: Forbidden imports ────────────────────────────────────────────────────
//
// Skill rule (backend-workflows/SKILL.md):
// "Prefer imports from @drumr/framework-backend."
// Pitfalls: "Hallucinating DBOS imports directly", "generic worker patterns (BullMQ,
// agenda, node-cron)"
//
describe('SR-4 — source files do not import from forbidden libraries', () => {
	const readSource = (relPath: string) =>
		fs.readFileSync(path.resolve(__dirname, '../../../src', relPath), 'utf8');

	const syncDataSource = readSource('global/workflows/sync-data.workflow.ts');
	const archiveSource = readSource(
		'projects/workflows/archive-project.workflow.ts',
	);
	const cleanupSource = readSource(
		'global/workflows/scheduled/daily-inactive-tasks-cleanup.workflow.ts',
	);

	describe('SyncDataWorkflow', () => {
		it('does not import directly from @dbos-inc packages', () => {
			// Skill pitfall: "Hallucinating DBOS imports directly."
			// All DBOS primitives must come through @drumr/framework-backend.
			expect(syncDataSource).not.toMatch(/from ['"]@dbos-inc/);
		});

		it('does not use generic queue workers (bullmq, agenda, node-cron)', () => {
			expect(syncDataSource).not.toMatch(/from ['"]bullmq['"]/);
			expect(syncDataSource).not.toMatch(/from ['"]agenda['"]/);
			expect(syncDataSource).not.toMatch(/from ['"]node-cron['"]/);
		});

		it('primary framework import is from "@drumr/framework-backend"', () => {
			expect(syncDataSource).toMatch(/from ['"]@drumr\/framework-backend['"]/);
		});
	});

	describe('ArchiveProjectWorkflow', () => {
		it('does not import directly from @dbos-inc packages', () => {
			expect(archiveSource).not.toMatch(/from ['"]@dbos-inc/);
		});

		it('primary framework import is from "@drumr/framework-backend"', () => {
			expect(archiveSource).toMatch(/from ['"]@drumr\/framework-backend['"]/);
		});
	});

	describe('DailyInactiveTasksCleanupWorkflow', () => {
		it('does not import directly from @dbos-inc packages', () => {
			expect(cleanupSource).not.toMatch(/from ['"]@dbos-inc/);
		});

		it('does not use node-cron or agenda (cron belongs in @Workflow schedule option)', () => {
			// Skill: "Adding generic worker patterns (BullMQ, agenda, node-cron) — [forbidden]"
			expect(cleanupSource).not.toMatch(/from ['"]node-cron['"]/);
			expect(cleanupSource).not.toMatch(/from ['"]agenda['"]/);
		});

		it('primary framework import is from "@drumr/framework-backend"', () => {
			expect(cleanupSource).toMatch(/from ['"]@drumr\/framework-backend['"]/);
		});
	});
});
