/**
 * Skill Conformance Tests — backend-actions
 * Skill reference: core/skills/backend-actions/SKILL.md
 *
 * PURPOSE
 * -------
 * Proves that code generated by following the backend-actions skill satisfies
 * the skill's documented contracts rule by rule.
 *
 * Each `describe` block maps to a specific Skill Rule (SR-*) documented in
 * the skill. When a test fails, it means either:
 *   (a) the generated code does not follow the skill — the fixture needs updating, OR
 *   (b) the skill documents a pattern that doesn't hold in practice — the skill
 *       needs updating.
 *
 * FIXTURES
 * --------
 *   UpdateProjectStatus.ts  — ObjectAction with params, canExecute, execute
 *   SyncData.ts             — GlobalAction with no params, execute only
 *   ArchiveProject.ts       — ObjectAction with no params, canExecute, execute
 *
 * Using three fixtures (two action types) raises the Consistency dimension
 * score above the single-fixture baseline.
 *
 * HOW TO RUN
 * ----------
 * From apps/project-management-app/backend/:
 *   TS_NODE_PROJECT=tsconfig.test.json npx jest --config config/jest.config.ts \
 *     --testPathPatterns='backend-actions.skill-conformance' --no-coverage --verbose
 *
 * IMPORTANT: always pass --config config/jest.config.ts (ts-jest preset).
 */

import * as fs from 'fs';
import * as path from 'path';

// ─── Mock setup ────────────────────────────────────────────────────────────────
//
// Intercepts @drumr/framework-backend so the @Action decorator can be observed
// without triggering real DI registration or DB connections.
//
// capturedActions: Map<className, { options }> — populated as each action
// module is loaded and its decorator executes.
//
// DataModel and Indexes are explicit pass-throughs (not noop) because the params
// class (UpdateProjectStatusParams) is referenced by value inside @Action options.
// A noop would replace the class with `undefined`, making opts.params undefined.
//
// NOTE: jest.mock is hoisted to the top of the file at compile time.

jest.mock('@drumr/framework-backend', () => {
	class MockGlobalAction {}
	class MockModelAction {}
	class MockObjectAction {}
	class MockBaseDataModel {}

	const capturedActions: Map<string, { options: any }> = new Map();

	// Property decorators: return () => undefined (no assignment needed).
	function noop(..._args: any[]) {
		return (..._rest: any[]) => undefined;
	}

	// Class decorators that must preserve the class (pass-through).
	function classPassThrough(_opts: any) {
		return (cls: any) => cls;
	}

	const explicit: Record<string, any> = {
		_capturedActions: capturedActions,
		GlobalAction: MockGlobalAction,
		ModelAction: MockModelAction,
		ObjectAction: MockObjectAction,
		BaseDataModel: MockBaseDataModel,

		// Captured decorator — records options per action class name.
		Action: (opts: any) => (cls: any) => {
			capturedActions.set(cls.name, { options: opts ?? {} });
			return cls;
		},

		// Pass-throughs: params class must remain a constructor when passed to @Action.
		DataModel: classPassThrough,
		Indexes: classPassThrough,

		// Workflow types used as plain values in @Action options.
		WorkflowExecution: class WorkflowExecution {},
		WorkflowsManager: class WorkflowsManager {},
	};

	return new Proxy(explicit, {
		get: (target, prop: string) => (prop in target ? target[prop] : noop),
	});
});

// Stub the mainDs datasource — prevents any DB connection attempt.
jest.mock('../../../src/config/data-sources/main/main.ds', () => ({
	MainDs: class MainDs {},
}));

// Stub workflow classes — prevents transitive imports from loading complex modules.
jest.mock('../../../src/global/workflows/sync-data.workflow', () => ({
	SyncDataWorkflow: class SyncDataWorkflow {},
}));
jest.mock('../../../src/projects/workflows/archive-project.workflow', () => ({
	ArchiveProjectWorkflow: class ArchiveProjectWorkflow {},
}));

import { SyncData } from '../../../src/global/actions/sync-data.action';
import { ArchiveProject } from '../../../src/projects/actions/archive-project.action';
import {
	UpdateProjectStatus,
	UpdateProjectStatusParams,
} from '../../../src/projects/actions/update-project-status.action';

const mock = jest.requireMock('@drumr/framework-backend') as {
	_capturedActions: Map<string, { options: any }>;
	GlobalAction: new () => object;
	ModelAction: new () => object;
	ObjectAction: new () => object;
};

// ─── SR-1: Decorator contract ──────────────────────────────────────────────────
//
// Skill rule (backend-actions/SKILL.md):
// "All configuration lives inside the decorator — no static getters needed."
// "@Action({ type: 'write'|'read', model, params, returns, api, ui })"
// "type: 'write' for mutations, 'read' for queries — required"
//
describe('SR-1 — @Action() decorator is used with required options (never undecorated)', () => {
	describe('UpdateProjectStatus — ObjectAction with params', () => {
		it('class is decorated with @Action()', () => {
			expect(mock._capturedActions.has('UpdateProjectStatus')).toBe(true);
		});

		it('@Action() declares a type option ("read" or "write")', () => {
			const opts = mock._capturedActions.get('UpdateProjectStatus')!.options;
			expect(['read', 'write']).toContain(opts.type);
		});

		it('@Action() declares a model option (required for ObjectAction)', () => {
			// Skill: ModelAction and ObjectAction require the model option.
			const opts = mock._capturedActions.get('UpdateProjectStatus')!.options;
			expect(opts.model).toBeDefined();
		});

		it('@Action() declares an api option exposing it via GraphQL', () => {
			const opts = mock._capturedActions.get('UpdateProjectStatus')!.options;
			expect(opts.api).toBe('gql');
		});

		it('@Action() declares a ui.label string', () => {
			const opts = mock._capturedActions.get('UpdateProjectStatus')!.options;
			expect(typeof opts.ui?.label).toBe('string');
			expect((opts.ui!.label as string).length).toBeGreaterThan(0);
		});

		it('@Action() declares a params class (input parameters are documented)', () => {
			// Skill: "Define params @DataModel in same file, directly above the action class."
			const opts = mock._capturedActions.get('UpdateProjectStatus')!.options;
			expect(opts.params).toBeDefined();
			expect(typeof opts.params).toBe('function'); // must be a constructor
		});
	});

	describe('SyncData — GlobalAction with no params', () => {
		it('class is decorated with @Action()', () => {
			expect(mock._capturedActions.has('SyncData')).toBe(true);
		});

		it('@Action() declares a type option', () => {
			const opts = mock._capturedActions.get('SyncData')!.options;
			expect(['read', 'write']).toContain(opts.type);
		});

		it('@Action() for GlobalAction does NOT declare a model option', () => {
			// Skill: GlobalAction is "not tied to any entity". model must be absent.
			const opts = mock._capturedActions.get('SyncData')!.options;
			expect(opts.model).toBeUndefined();
		});

		it('@Action() declares a ui.label string', () => {
			const opts = mock._capturedActions.get('SyncData')!.options;
			expect(typeof opts.ui?.label).toBe('string');
			expect((opts.ui!.label as string).length).toBeGreaterThan(0);
		});
	});

	describe('ArchiveProject — ObjectAction with no params', () => {
		it('class is decorated with @Action()', () => {
			expect(mock._capturedActions.has('ArchiveProject')).toBe(true);
		});

		it('@Action() declares a model option (required for ObjectAction)', () => {
			const opts = mock._capturedActions.get('ArchiveProject')!.options;
			expect(opts.model).toBeDefined();
		});

		it('@Action() declares a ui.label string', () => {
			const opts = mock._capturedActions.get('ArchiveProject')!.options;
			expect(typeof opts.ui?.label).toBe('string');
			expect((opts.ui!.label as string).length).toBeGreaterThan(0);
		});
	});
});

// ─── SR-2: Base class contract ─────────────────────────────────────────────────
//
// Skill rule (backend-actions/SKILL.md):
// "GlobalAction<P, R>  — not tied to any entity"
// "ModelAction<M, P, R> — collection-level"
// "ObjectAction<M, P, R> — operations on a specific record instance"
//
// Each action class must extend the correct framework base class.
// Wrong base class = wrong canExecute signature = silent runtime bug.
//
describe('SR-2 — action class extends the correct framework base class', () => {
	it('UpdateProjectStatus extends ObjectAction via prototype chain', () => {
		expect(UpdateProjectStatus.prototype).toBeInstanceOf(mock.ObjectAction);
	});

	it('SyncData extends GlobalAction via prototype chain', () => {
		expect(SyncData.prototype).toBeInstanceOf(mock.GlobalAction);
	});

	it('ArchiveProject extends ObjectAction via prototype chain', () => {
		expect(ArchiveProject.prototype).toBeInstanceOf(mock.ObjectAction);
	});
});

// ─── SR-3: execute() behavioral contract ───────────────────────────────────────
//
// Skill rule (backend-actions/SKILL.md):
// "execute(target?, params?) — after validation. The core action logic. Required."
// "canExecute(entity: M): Promise<boolean | string> — for ObjectAction."
// "Preferred — explains WHY execution was blocked."
//
describe('SR-3 — execute() and canExecute() contracts', () => {
	describe('UpdateProjectStatus (ObjectAction with params)', () => {
		it('execute() method exists on the prototype', () => {
			expect(typeof UpdateProjectStatus.prototype.execute).toBe('function');
		});

		it('execute() is async (returns a Promise)', () => {
			const ds = { save: jest.fn().mockResolvedValue(null) };
			const instance = new UpdateProjectStatus(ds as any);
			// Provide just enough shape to avoid a null-reference in the method body.
			const project = {
				status: 'active',
				updatedAt: null,
				endDate: null,
				completionPercentage: 0,
			} as any;
			const params = { status: 'completed' } as any;
			const result = instance.execute(project, params);
			expect(result).toBeInstanceOf(Promise);
			// Resolve the promise so Jest does not flag an unhandled rejection.
			return result.catch(() => undefined);
		});

		it('canExecute() method exists on the prototype', () => {
			// Skill: ObjectAction.canExecute(entity: M) is the guard hook.
			expect(typeof UpdateProjectStatus.prototype.canExecute).toBe('function');
		});

		it('canExecute() returns true for a project in a valid transition state', async () => {
			const ds = { save: jest.fn() };
			const instance = new UpdateProjectStatus(ds as any);
			const result = await instance.canExecute({ status: 'active' } as any);
			// Skill: "Return false or a string to block execution."
			expect(result === true || typeof result === 'string').toBe(true);
			expect(result).toBe(true);
		});

		it('canExecute() returns a string (reason) for a cancelled project', async () => {
			const ds = { save: jest.fn() };
			const instance = new UpdateProjectStatus(ds as any);
			const result = await instance.canExecute({ status: 'cancelled' } as any);
			// Skill: "Return a string to block execution — the string is the reason."
			expect(typeof result).toBe('string');
			expect((result as string).length).toBeGreaterThan(0);
		});
	});

	describe('SyncData (GlobalAction, no params)', () => {
		it('execute() method exists on the prototype', () => {
			expect(typeof SyncData.prototype.execute).toBe('function');
		});

		it('execute() is async (returns a Promise)', () => {
			const workflowsManager = { execute: jest.fn().mockResolvedValue({}) };
			const instance = new SyncData(workflowsManager as any);
			const result = instance.execute();
			expect(result).toBeInstanceOf(Promise);
			return result.catch(() => undefined);
		});
	});

	describe('ArchiveProject (ObjectAction, no params)', () => {
		it('canExecute() method exists on the prototype', () => {
			expect(typeof ArchiveProject.prototype.canExecute).toBe('function');
		});

		it('canExecute() returns true for a project that is not archived', async () => {
			const workflowsManager = { execute: jest.fn() };
			const instance = new ArchiveProject(workflowsManager as any);
			const result = await instance.canExecute({ isArchived: false } as any);
			expect(result).toBe(true);
		});

		it('canExecute() returns a string for an already-archived project', async () => {
			const workflowsManager = { execute: jest.fn() };
			const instance = new ArchiveProject(workflowsManager as any);
			const result = await instance.canExecute({ isArchived: true } as any);
			expect(typeof result).toBe('string');
			expect((result as string).length).toBeGreaterThan(0);
		});
	});
});

// ─── SR-4: Forbidden imports ───────────────────────────────────────────────────
//
// Skill rule (backend-actions/SKILL.md):
// "Do not import from 'tsyringe' directly — use @drumr/framework-backend exports exclusively."
// "Do not add @injectable() to an action class — @Action already handles DI registration."
// "Do not use @inject() for class-type tokens."
//
describe('SR-4 — source files do not import from forbidden libraries', () => {
	const readFixture = (relativePath: string) =>
		fs.readFileSync(path.resolve(__dirname, relativePath), 'utf8');

	const updateProjectStatusSource = readFixture(
		'../../../src/projects/actions/update-project-status.action.ts',
	);
	const syncDataSource = readFixture(
		'../../../src/global/actions/sync-data.action.ts',
	);
	const archiveProjectSource = readFixture(
		'../../../src/projects/actions/archive-project.action.ts',
	);

	describe('UpdateProjectStatus.ts', () => {
		it('does not import from "tsyringe" directly', () => {
			expect(updateProjectStatusSource).not.toMatch(/from ['"]tsyringe['"]/);
		});

		it('does not use @injectable() or @inject() decorators', () => {
			// Skill: "@Action already handles DI registration — no @injectable() needed."
			expect(updateProjectStatusSource).not.toMatch(/@injectable\s*\(/);
			expect(updateProjectStatusSource).not.toMatch(/@inject\s*\(/);
		});

		it('primary framework import is from "@drumr/framework-backend"', () => {
			expect(updateProjectStatusSource).toMatch(
				/from ['"]@drumr\/framework-backend['"]/,
			);
		});
	});

	describe('SyncData.ts', () => {
		it('does not import from "tsyringe" directly', () => {
			expect(syncDataSource).not.toMatch(/from ['"]tsyringe['"]/);
		});

		it('does not use @injectable() or @inject() decorators', () => {
			expect(syncDataSource).not.toMatch(/@injectable\s*\(/);
			expect(syncDataSource).not.toMatch(/@inject\s*\(/);
		});

		it('primary framework import is from "@drumr/framework-backend"', () => {
			expect(syncDataSource).toMatch(/from ['"]@drumr\/framework-backend['"]/);
		});
	});

	describe('ArchiveProject.ts', () => {
		it('does not import from "tsyringe" directly', () => {
			expect(archiveProjectSource).not.toMatch(/from ['"]tsyringe['"]/);
		});

		it('does not use @injectable() or @inject() decorators', () => {
			expect(archiveProjectSource).not.toMatch(/@injectable\s*\(/);
			expect(archiveProjectSource).not.toMatch(/@inject\s*\(/);
		});

		it('primary framework import is from "@drumr/framework-backend"', () => {
			expect(archiveProjectSource).toMatch(
				/from ['"]@drumr\/framework-backend['"]/,
			);
		});
	});
});

// ─── SR-4 adversarial: repo-wide scan — all src/actions/**/*.ts ────────────────
//
// Skill rules (backend-actions/SKILL.md § Don't):
// "Do not import from 'tsyringe' directly — use @drumr/framework-backend exports exclusively."
// "Do not add @injectable() to an action class — @Action already handles DI registration."
// "Do not use @inject() for class-type tokens."
//
// A repo-wide scan raises R from 1 to 2 by covering every action file,
// not just the three primary fixtures.
//
describe('SR-4 adversarial — repo-wide scan: all src/actions/**/*.ts', () => {
	function collectActionSources(
		dir: string,
	): Array<{ file: string; source: string }> {
		const results: Array<{ file: string; source: string }> = [];
		for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
			const fullPath = path.join(dir, entry.name);
			if (entry.isDirectory()) {
				results.push(...collectActionSources(fullPath));
			} else if (entry.name.endsWith('.ts') && !entry.name.endsWith('.d.ts')) {
				results.push({
					file: fullPath,
					source: fs.readFileSync(fullPath, 'utf8'),
				});
			}
		}
		return results;
	}

	const actionsDir = path.resolve(__dirname, '../../../src/actions');
	const allActionSources = collectActionSources(actionsDir);

	it('no action file imports from "tsyringe" directly', () => {
		// Skill: "Import from @drumr/framework-backend exclusively."
		const violations = allActionSources.filter((f) =>
			/(from\s+['"]tsyringe['"]|require\(\s*['"]tsyringe['"]\s*\)|import\(\s*['"]tsyringe['"]\s*\))/.test(
				f.source,
			),
		);
		expect(violations.map((f) => f.file)).toHaveLength(0);
	});

	it('no action file uses @injectable() decorator', () => {
		// Skill: "@Action already handles DI registration — @injectable() is forbidden."
		const violations = allActionSources.filter((f) =>
			/@injectable\s*\(/.test(f.source),
		);
		expect(violations.map((f) => f.file)).toHaveLength(0);
	});

	it('no action file uses @inject() decorator', () => {
		// Skill: "Do not use @inject() for class-type tokens."
		const violations = allActionSources.filter((f) =>
			/@inject\s*\(/.test(f.source),
		);
		expect(violations.map((f) => f.file)).toHaveLength(0);
	});
});
