/**
 * Skill Conformance Tests — backend-datasources
 * Skill reference: core/skills/backend-datasources/SKILL.md
 *
 * PURPOSE
 * -------
 * Proves that code generated by following the backend-datasources skill satisfies
 * the skill's documented contracts rule by rule.
 *
 * Each `describe` block maps to a specific Skill Rule (SR-*) documented in
 * the skill. When a test fails, it means either:
 *   (a) the generated code does not follow the skill — the fixture needs updating, OR
 *   (b) the skill documents a pattern that doesn't hold in practice — the skill
 *       needs updating.
 *
 * FIXTURES
 * --------
 *   mainDs.ts                    — live import + source text: @DataSource, type,
 *                                  managed, env-var connection fields
 *   ArchiveCompletedProjects.ts  — source text: findAndPaginate for bulk iteration,
 *                                  constructor injection, transaction usage
 *   Project.ts / Task.ts         — source text: no raw ORM imports, datasource
 *                                  reference present in @DataModel
 *
 * HOW TO RUN
 * ----------
 * From apps/project-management-app/backend/:
 *   TS_NODE_PROJECT=tsconfig.test.json npx jest --config config/jest.config.ts \
 *     --testPathPatterns='backend-datasources.skill-conformance' --no-coverage --verbose
 *
 * IMPORTANT: always pass --config config/jest.config.ts (ts-jest preset).
 */

import * as fs from 'fs';
import * as path from 'path';

// ─── Mock setup ────────────────────────────────────────────────────────────────
//
// Intercepts @drumr/framework-backend so the @DataSource decorator can be
// observed and TypeOrmSqlDataSource can be used as a mock base class, without
// triggering any real DB connection attempts.
//
// capturedDataSources: Map<className, { options }> — populated as each
// datasource module is loaded and its decorator executes.
//
// NOTE: jest.mock is hoisted to the top of the file at compile time.

jest.mock('@drumr/framework-backend', () => {
	class MockTypeOrmSqlDataSource {}

	const capturedDataSources: Map<string, { options: any }> = new Map();

	// Property decorators: return () => undefined (no assignment needed).
	function noop(..._args: any[]) {
		return (..._rest: any[]) => undefined;
	}

	const explicit: Record<string, any> = {
		_capturedDataSources: capturedDataSources,
		TypeOrmSqlDataSource: MockTypeOrmSqlDataSource,

		// Captured decorator — records options per datasource class name.
		DataSource: (opts?: any) => (cls: any) => {
			capturedDataSources.set(cls.name, { options: opts ?? {} });
			return cls;
		},
	};

	return new Proxy(explicit, {
		get: (target, prop: string) => (prop in target ? target[prop] : noop),
	});
});

import { MainDs } from '../../../src/config/data-sources/main/main.ds';

const mock = jest.requireMock('@drumr/framework-backend') as {
	_capturedDataSources: Map<string, { options: any }>;
	TypeOrmSqlDataSource: new () => object;
};

// ─── Source files for static assertions ───────────────────────────────────────

const mainDsSource = fs.readFileSync(
	path.resolve(__dirname, '../../../src/config/data-sources/main/main.ds.ts'),
	'utf8',
);

const archiveProjectsSource = fs.readFileSync(
	path.resolve(
		__dirname,
		'../../../src/global/actions/archive-completed-projects.action.ts',
	),
	'utf8',
);

const projectSource = fs.readFileSync(
	path.resolve(
		__dirname,
		'../../../src/projects/data-models/project.data-model.ts',
	),
	'utf8',
);

const taskSource = fs.readFileSync(
	path.resolve(__dirname, '../../../src/tasks/data-models/task.data-model.ts'),
	'utf8',
);

// ─── Helper ───────────────────────────────────────────────────────────────────

/** Recursively collects all .ts files (excluding .d.ts) under a directory. */
function getAllTsFiles(dir: string): string[] {
	const entries = fs.readdirSync(dir, { withFileTypes: true });
	const files: string[] = [];
	for (const entry of entries) {
		const full = path.join(dir, entry.name);
		if (entry.isDirectory()) {
			files.push(...getAllTsFiles(full));
		} else if (entry.name.endsWith('.ts') && !entry.name.endsWith('.d.ts')) {
			files.push(full);
		}
	}
	return files;
}

// ─── SR-1: @DataSource() decorator contract ───────────────────────────────────
//
// Skill rule (backend-datasources/SKILL.md):
// "Create one datasource class … and decorate it with @DataSource(…)."
// "Prefer providing an explicit datasource `id`."
// "id (optional in decorator, strongly recommended): datasource identifier
//  used by CLI/runtime conventions."
//
describe('SR-1 — @DataSource() decorator is used with an explicit id option', () => {
	it('MainDs is decorated with @DataSource()', () => {
		// Without @DataSource the runtime will not discover or register the class,
		// causing silent "datasource not found" failures at startup.
		expect(mock._capturedDataSources.has('MainDs')).toBe(true);
	});

	it('@DataSource() declares an explicit id option', () => {
		// Skill: "Prefer providing an explicit datasource `id` in @DataSource(…)
		// for predictable dataset paths and CLI usage."
		const opts = mock._capturedDataSources.get('MainDs')!.options;
		expect(typeof opts.id).toBe('string');
		expect(opts.id.length).toBeGreaterThan(0);
	});
});

// ─── SR-2: Base class and required properties ─────────────────────────────────
//
// Skill rule (backend-datasources/SKILL.md):
// "class … extends TypeOrmSqlDataSource"
// "type (required): SQL engine"
// "managed (required): enables Drumr-managed schema behavior"
//
describe('SR-2 — MainDs extends TypeOrmSqlDataSource with required properties', () => {
	it('MainDs extends TypeOrmSqlDataSource via prototype chain', () => {
		// TypeOrmSqlDataSource is the only supported base class for SQL datasources.
		// Extending a raw TypeORM DataSource directly bypasses Drumr's managed
		// schema behavior and datasource registry.
		expect(MainDs.prototype).toBeInstanceOf(mock.TypeOrmSqlDataSource);
	});

	it('MainDs instance has a `type` property (required)', () => {
		// Skill: "`type` (required): SQL engine"
		// The instance property initializer runs at construction time.
		const instance = new MainDs();
		expect((instance as any).type).toBeDefined();
	});

	it('`type` is a known SQL engine string', () => {
		// Skill lists valid values: 'postgres', 'mysql', 'mariadb', 'sqlite', 'mssql', 'oracle'.
		// An invalid engine silently fails at connection time.
		const validEngines = [
			'postgres',
			'mysql',
			'mariadb',
			'sqlite',
			'mssql',
			'oracle',
		];
		const instance = new MainDs();
		expect(validEngines).toContain((instance as any).type);
	});

	it('MainDs instance has `managed = true` (required)', () => {
		// Skill: "`managed` (required): enables Drumr-managed schema behavior; use consciously."
		// Without `managed = true` the framework won't register this datasource for
		// schema management and dataset operations.
		const instance = new MainDs();
		expect((instance as any).managed).toBe(true);
	});
});

// ─── SR-3: Environment-variable-driven connection properties ──────────────────
//
// Skill rule (backend-datasources/SKILL.md):
// "Use env vars for connection fields, not hardcoded credentials."
// Copilot guidance #3: "Use env vars for connection fields, not hardcoded credentials."
//
describe('SR-3 — connection properties are driven by environment variables', () => {
	it('host reads from process.env.DB_HOST', () => {
		// Hardcoding a DB host prevents environment parity between dev/staging/prod.
		expect(mainDsSource).toMatch(/process\.env\.DB_HOST/);
	});

	it('port reads from process.env.DB_PORT', () => {
		expect(mainDsSource).toMatch(/process\.env\.DB_PORT/);
	});

	it('username reads from process.env.DB_USER', () => {
		expect(mainDsSource).toMatch(/process\.env\.DB_USER/);
	});

	it('password reads from process.env.DB_PASSWORD', () => {
		// Hardcoded passwords are a security violation (OWASP A02: Cryptographic Failures).
		expect(mainDsSource).toMatch(/process\.env\.DB_PASSWORD/);
	});

	it('database reads from process.env.DB_NAME', () => {
		expect(mainDsSource).toMatch(/process\.env\.DB_NAME/);
	});

	it('datasource source does not contain hardcoded connection strings (no jdbc:// or mongodb://)', () => {
		// Belt-and-suspenders check: if someone sneaks a connection string literal in,
		// these patterns will catch it.
		expect(mainDsSource).not.toMatch(/jdbc:\/\//);
		expect(mainDsSource).not.toMatch(/mongodb:\/\//);
		expect(mainDsSource).not.toMatch(/postgresql:\/\//);
	});
});

// ─── SR-4: Model-to-datasource linking (no raw ORM imports) ──────────────────
//
// Skill rule (backend-datasources/SKILL.md):
// "Preferred standard: link models by datasource class."
// "Do not use datasource string references in new code."
// Inferred: raw typeorm/sequelize/mongoose imports in model files are forbidden
// because Drumr encapsulates all ORM access behind the datasource abstraction.
//
describe('SR-4 — data models reference the datasource and avoid raw ORM imports', () => {
	it('Project.ts does NOT import directly from "typeorm"', () => {
		// Skill: datasource abstraction is the only sanctioned ORM entry point.
		expect(projectSource).not.toMatch(/from ['"]typeorm['"]/);
	});

	it('Task.ts does NOT import directly from "typeorm"', () => {
		expect(taskSource).not.toMatch(/from ['"]typeorm['"]/);
	});

	it('Project.ts does NOT import from "sequelize" or "mongoose"', () => {
		expect(projectSource).not.toMatch(/from ['"]sequelize['"]/);
		expect(projectSource).not.toMatch(/from ['"]mongoose['"]/);
	});

	it('Project.ts references the datasource via @DataModel({ dataSource: ... })', () => {
		// Skill documents two valid forms:
		//   (a) class reference  → `dataSource: MainDs`  (preferred)
		//   (b) string id        → `dataSource: 'postgres-db'`  (legacy, still valid)
		// Either form must be present; the key must not be omitted entirely.
		const hasClassRef = projectSource.includes('dataSource: MainDs');
		const hasStringRef = /dataSource:\s*['"][^'"]+['"]/.test(projectSource);
		expect(hasClassRef || hasStringRef).toBe(true);
	});

	it('Task.ts references the datasource via @DataModel({ dataSource: ... })', () => {
		const hasClassRef = taskSource.includes('dataSource: MainDs');
		const hasStringRef = /dataSource:\s*['"][^'"]+['"]/.test(taskSource);
		expect(hasClassRef || hasStringRef).toBe(true);
	});
});

// ─── SR-5: Query method contracts (critical rules) ───────────────────────────
//
// Skill rule (backend-datasources/SKILL.md §Copilot guidance):
//
// 8. "Never call `find()` or `findBy()` expecting all records."
// 9. "Never write `result.objects` as if it contained all matching entities."
// 10."NEVER call `this.ds.findById()` — this method does NOT exist on the datasource."
//    "findById is only the name of an auto-generated CRUD API action exposed via GraphQL."
//
// SR-5a: findById is a common naming pitfall — this is explicitly flagged in the skill.
//
describe('SR-5 — query methods follow skill contracts (critical)', () => {
	describe('SR-5a — this.ds.findById() is never called on a datasource instance', () => {
		it('ArchiveCompletedProjects does not call this.ds.findById()', () => {
			// Skill CRITICAL: "findById does NOT exist on the datasource."
			// Calling it causes a runtime TypeError — "this.ds.findById is not a function."
			expect(archiveProjectsSource).not.toMatch(/this\.ds\.findById\(/);
		});

		it('no action source file calls this.ds.findById() on the datasource', () => {
			// Repository-wide check to catch any action that misuses findById.
			// If this test fails, the output will list the offending files.
			const srcRoot = path.resolve(__dirname, '../../../src');
			const actionFiles: string[] = [];
			for (const mod of fs.readdirSync(srcRoot)) {
				const actionsDir = path.join(srcRoot, mod, 'actions');
				if (
					fs.existsSync(actionsDir) &&
					fs.statSync(actionsDir).isDirectory()
				) {
					actionFiles.push(...getAllTsFiles(actionsDir));
				}
			}
			const violations = actionFiles.filter((file) =>
				fs.readFileSync(file, 'utf8').includes('this.ds.findById('),
			);
			expect(violations).toHaveLength(0);
		});

		it('no service source file calls this.ds.findById() on the datasource', () => {
			const srcRoot = path.resolve(__dirname, '../../../src');
			const serviceFiles: string[] = [];
			for (const mod of fs.readdirSync(srcRoot)) {
				const servicesDir = path.join(srcRoot, mod, 'services');
				if (
					fs.existsSync(servicesDir) &&
					fs.statSync(servicesDir).isDirectory()
				) {
					serviceFiles.push(...getAllTsFiles(servicesDir));
				}
			}
			const violations = serviceFiles.filter((file) =>
				fs.readFileSync(file, 'utf8').includes('this.ds.findById('),
			);
			expect(violations).toHaveLength(0);
		});
	});

	describe('SR-5b — findAndPaginate is used for full-table iteration', () => {
		it('ArchiveCompletedProjects uses findAndPaginate for bulk iteration (not find/findBy)', () => {
			// Skill: "findAndPaginate() automatically pages through ALL matches. Use for
			// bulk processing, migrations, exports, background jobs, and any logic that
			// must see every matching row."
			// ArchiveCompletedProjects processes every completed project — exactly this pattern.
			expect(archiveProjectsSource).toMatch(/this\.ds\.findAndPaginate\(/);
		});

		it('ArchiveCompletedProjects collects results via the findAndPaginate callback', () => {
			// The pattern: `findAndPaginate(..., async (record) => { ... })`
			// Verifies the callback form, not a result-object assumption.
			expect(archiveProjectsSource).toMatch(
				/findAndPaginate\s*\([\s\S]*?async\s*\(/,
			);
		});
	});

	describe('SR-5c — datasource is injected via constructor (not directly instantiated)', () => {
		it('ArchiveCompletedProjects receives MainDs as a constructor parameter', () => {
			// Skill: "Use datasource injection when you need transactions or native DB access."
			// Injection: `constructor(private ds: MainDs)`
			expect(archiveProjectsSource).toMatch(/private\s+ds\s*:\s*MainDs/);
		});

		it('ArchiveCompletedProjects does not instantiate MainDs with `new`', () => {
			// Direct instantiation bypasses the DI container and produces an
			// unconfigured datasource with no connection pool.
			expect(archiveProjectsSource).not.toMatch(/new\s+MainDs\s*\(/);
		});
	});

	describe('SR-5d — transactions wrap multi-step writes', () => {
		it('ArchiveCompletedProjects uses this.ds.transaction() for its write loop', () => {
			// Skill: "Add transactional boundaries only for multi-step write consistency."
			// ArchiveCompletedProjects saves many projects — a transaction ensures all-or-nothing.
			expect(archiveProjectsSource).toMatch(/this\.ds\.transaction\s*\(/);
		});
	});
});
