/**
 * Skill Conformance Tests — frontend-app
 * Skill reference: core/skills/frontend-app/SKILL.md
 *
 * PURPOSE
 * -------
 * Proves that code generated by following the frontend-app skill satisfies the
 * skill's documented contracts rule by rule.
 *
 * Each `describe` block maps to a specific Skill Rule (SR-*) documented in
 * the skill. When a test fails, it means either:
 *   (a) the generated code does not follow the skill — the fixture needs updating, OR
 *   (b) the skill documents a pattern that doesn't hold in practice — the skill
 *       needs updating.
 *
 * FIXTURES
 * --------
 * The frontend bootstrap is split into three files (functional pattern):
 *
 *   frontend/src/app.ts          — App(fn) call + lifecycle hooks (beforeStart,
 *                                  afterStart, beforeUnmount, onError) and
 *                                  re-exports of UmiJS runtime symbols.
 *   frontend/src/config/appDefaults.ts
 *                                — defineAppDefaults({...}) with app-wide
 *                                  configuration (appName, defaultLayout,
 *                                  viewsContext, locale, layoutSettings, etc.).
 *
 * Backend Jest has no TSX/frontend transform. All SR-* contracts are
 * verifiable from source text (import declarations, function shape, factory
 * presence, property assignments, UMI exports).
 *
 * SkillScore (initial):
 *   C=3 (SR-1+SR-2+SR-3 all covered)
 *   K=3 (app bootstrap files are the only entry surface — K=3 per formula cap)
 *   D=3 (structural invariant)
 *   R=2 (SR-4 + adversarial scan for anti-patterns)
 *   Score = (3×0.40 + 3×0.20 + 3×0.20 + 2×0.20) × 33.33 = 93.3
 *
 * HOW TO RUN
 * ----------
 * From apps/project-management-app/backend/:
 *   TS_NODE_PROJECT=tsconfig.test.json npx jest --config config/jest.config.ts \
 *     --testPathPatterns='frontend-app.skill-conformance' --no-coverage --verbose
 *
 * IMPORTANT: always pass --config config/jest.config.ts (ts-jest preset).
 */

import * as fs from 'fs';
import * as path from 'path';

// ─── Fixture loading ───────────────────────────────────────────────────────────
//
// __dirname    = apps/project-management-app/backend/tests/unit/skill-conformance
// FRONTEND_SRC = apps/project-management-app/frontend/src

/**
 * Skill Conformance Tests — frontend-app
 * Skill reference: core/skills/frontend-app/SKILL.md
 *
 * PURPOSE
 * -------
 * Proves that code generated by following the frontend-app skill satisfies the
 * skill's documented contracts rule by rule.
 *
 * Each `describe` block maps to a specific Skill Rule (SR-*) documented in
 * the skill. When a test fails, it means either:
 *   (a) the generated code does not follow the skill — the fixture needs updating, OR
 *   (b) the skill documents a pattern that doesn't hold in practice — the skill
 *       needs updating.
 *
 * FIXTURES
 * --------
 * The frontend bootstrap is split into configuration functions:
 *
 *   frontend/src/app.ts          — Invokes configureApp(app) on startup and
 *                                  re-exports of UmiJS runtime symbols.
 *   frontend/src/config/appDefaults.ts
 *                                — app.registerDefaults({...}) with app-wide
 *                                  configuration (appName, defaultLayout,
 *                                  locale, layoutSettings, etc.).
 *
 * Backend Jest has no TSX/frontend transform. All SR-* contracts are
 * verifiable from source text (import declarations, function shape, factory
 * presence, property assignments, UMI exports).
 *
 * SkillScore (initial):
 *   C=3 (SR-1+SR-2+SR-3 all covered)
 *   K=3 (app bootstrap files are the only entry surface — K=3 per formula cap)
 *   D=3 (structural invariant)
 *   R=2 (SR-4 + adversarial scan for anti-patterns)
 *   Score = (3×0.40 + 3×0.20 + 3×0.20 + 2×0.20) × 33.33 = 93.3
 *
 * HOW TO RUN
 * ----------
 * From apps/project-management-app/backend/:
 *   TS_NODE_PROJECT=tsconfig.test.json npx jest --config config/jest.config.ts \
 *     --testPathPatterns='frontend-app.skill-conformance' --no-coverage --verbose
 *
 * IMPORTANT: always pass --config config/jest.config.ts (ts-jest preset).
 */

// ─── Fixture loading ───────────────────────────────────────────────────────────
//
// __dirname    = apps/project-management-app/backend/tests/unit/skill-conformance
// FRONTEND_SRC = apps/project-management-app/frontend/src

const FRONTEND_SRC = path.resolve(__dirname, '../../../../frontend/src');

const appSrc = fs.readFileSync(path.join(FRONTEND_SRC, 'app.ts'), 'utf-8');
const appDefaultsSrc = fs.readFileSync(
	path.join(FRONTEND_SRC, 'config/appDefaults.ts'),
	'utf-8',
);

// ─── SR-1: Import / factory contracts ─────────────────────────────────────────

describe('SR-1: Import and factory contracts', () => {
	// Rule: "Import app from @drumr/framework-frontend"
	it('app.ts: imports app from @drumr/framework-frontend', () => {
		expect(appSrc).toMatch(/from\s+['"]@drumr\/framework-frontend['"]/);
		expect(appSrc).toMatch(/\bapp\b/);
	});

	// Rule: "Re-export runtime symbols from @drumr/framework-frontend/runtime"
	it('app.ts: re-exports runtime symbols directly', () => {
		expect(appSrc).toMatch(
			/export\s+\*\s+from\s+['"]@drumr\/framework-frontend\/runtime['"]/,
		);
	});
});

// ─── SR-2: Structural contracts ───────────────────────────────────────────────

describe('SR-2: Structural contracts', () => {
	// Rule: "Orchestrate configuration in app.ts"
	it('app.ts: imports configureApp and invokes it with app on module init', () => {
		expect(appSrc).toMatch(
			/import\s+\{\s*configureApp\s*\}\s+from\s+['"]\.\/config\/appConfig['"]/,
		);
		expect(appSrc).toMatch(/\bconfigureApp\s*\(\s*app\s*\)/);
	});
});

// ─── SR-3: Behavioral / property guarantees ───────────────────────────────────

describe('SR-3: Behavioral guarantees', () => {
	// Rule: "appName — identifies the app shell" (carried by app.registerDefaults)
	it('appDefaults.ts: app.registerDefaults sets appName', () => {
		expect(appDefaultsSrc).toMatch(
			/app\.registerDefaults\s*\(\s*\{[\s\S]*\bappName\s*:/,
		);
	});

	// Rule: "defaultLayout — Layout class for views that do not define their own layout"
	it('appDefaults.ts: app.registerDefaults sets defaultLayout', () => {
		expect(appDefaultsSrc).toMatch(/\bdefaultLayout\s*:/);
	});

	// Rule: "locale — Ant Design locale object for the app"
	it('appDefaults.ts: app.registerDefaults sets locale', () => {
		expect(appDefaultsSrc).toMatch(/\blocale\s*:/);
	});

	// Rule: "layoutSettings — Global layout settings at app shell level"
	// (fixSiderbar with 'er' is the correct spelling per framework types)
	it('appDefaults.ts: sets layoutSettings and uses fixSiderbar (framework spelling)', () => {
		expect(appDefaultsSrc).toMatch(/\blayoutSettings\s*:/);
		expect(appDefaultsSrc).toMatch(/fixSiderbar/);
	});
});

// ─── SR-4: Forbidden patterns + adversarial scan ─────────────────────────────

describe('SR-4: Forbidden patterns', () => {
	// Adversarial: app.ts must not import from internal framework paths
	it('app.ts: does not import from internal core/ paths', () => {
		expect(appSrc).not.toMatch(/from\s+['"].*\/core\/frontend\//);
		expect(appSrc).not.toMatch(/from\s+['"].*\/core\/src\//);
	});

	// Adversarial: app.ts must not manually create service instances with new
	// Rule: "Manual new Service() in views/components instead of DI — anti-pattern"
	// Note: DependencyContainer.instantiate(Service) is the framework-blessed
	// way to construct a singleton instance for registration, so it is not flagged.
	it('app.ts: no manual new Service() calls (use DI resolution)', () => {
		// Strip line comments before scanning so commented-out examples don't false-positive
		const strippedSrc = appSrc.replace(/\/\/.*$/gm, '');
		// Flag any direct `new FooService(` / `new FooRepository(` / `new FooAction(`
		// constructions outside of DependencyContainer.instantiate(...) calls.
		const bannedNew =
			strippedSrc.match(
				/(?<!instantiate\s*\(\s*)new\s+\w*(?:Service|Repository|Action)\s*\(/g,
			) ?? [];
		expect(bannedNew).toEqual([]);
	});
});
